### ISSUE TITLE
Can not resolve initial route when using setPathUrlStrategy

### ISSUE THREAD

**Issue by cerealexx** [Milad-Akarie/auto_route_library#1006]
When this plugin is used along with `setPathUrlStrategy()` to remove hash from web it throws the following error:
```
Error: Can not resolve initial route
    at Object.throw_ [as throw] ([http://localhost:45101/dart_sdk.js:5067:11]())
at routing_controller.AutoRouterDelegate.new.setInitialRoutePath ([http://localhost:45101/packages/auto_route/src/router/widgets/auto_tabs_scaffold.dart.lib.js:4815:19]())
    at _RootZone.runUnary ([http://localhost:45101/dart_sdk.js:40441:59]())
    at _FutureListener.then.handleValue ([http://localhost:45101/dart_sdk.js:35363:29]())
    at handleValueCallback ([http://localhost:45101/dart_sdk.js:35931:49]())
    at Function._propagateToListeners ([http://localhost:45101/dart_sdk.js:35969:17]())
    at _Future.new.[_completeWithValue] ([http://localhost:45101/dart_sdk.js:35817:23]())
    at [http://localhost:45101/dart_sdk.js:35758:39]()
at SynchronousFuture.new.then ([http://localhost:45101/packages/flutter/src/foundation/synchronous_future.dart.lib.js:39:22]())
    at _Future.new.[_chainForeignFuture] ([http://localhost:45101/dart_sdk.js:35754:18]())
    at Function._propagateToListeners ([http://localhost:45101/dart_sdk.js:35990:44]())
    at async._AsyncCallbackEntry.new.callback ([http://localhost:45101/dart_sdk.js:35698:27]())
```
Strangely enough, this only happens when you save a change in debug mode and then, if you save again, it just works.
This means I need to save changes two times in a row for the state to update correctly for every change I make.

**Comment by tstarasinic** [comment]
Try this: https://api.flutter.dev/flutter/flutter_web_plugins/PathUrlStrategy-class.html

**Comment by cerealexx** [comment]
I'm using [url_strategy](https://pub.dev/packages/url_strategy), which does the same.
The problem still persists using the PathUrlStrategy class though.

**Comment by cerealexx** [comment]
Nevermind, seems like it was solved regenerating code again.

**Comment by mahammadbakr** [comment]
@cerealexx i have same issue, any solution please ?!

**Comment by cerealexx** [comment]
@mahammadbakr calling `setPathUrlStrategy()` in my `main()` did the trick
