### ISSUE TITLE
When trying to reload the whole app that exception keeps throwing 'observer.navigator == null': is not true

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [Milad-Akarie/auto_route_library#101]

**Comment by slavap** [comment]
The same problem when trying to use Flutter dev tools "Select Widget Mode" button:
```
 ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (24018): The following assertion was thrown building Builder:
I/flutter (24018): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2590 pos 14:
I/flutter (24018): 'observer.navigator == null': is not true.
I/flutter (24018):
I/flutter (24018): The relevant error-causing widget was:
I/flutter (24018):   MaterialApp 
lib\app\themeable_app.dart:49
I/flutter (24018):
I/flutter (24018): When the exception was thrown, this was the stack:
I/flutter (24018): #2      NavigatorState.initState 
package:flutter/…/widgets/navigator.dart:2590
I/flutter (24018): #3      ExtendedNavigatorState.initState 
package:auto_route/src/extended_navigator.dart:103
I/flutter (24018): #4      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4644
I/flutter (24018): #5      ComponentElement.mount 
```

**Comment by AlaaEldeenYsr** [comment]
Yes that's actually happens when activating and deactivating the dev tool inspector, I had to use an older version

**Comment by vasilich6107** [comment]
What inspector tool are you working with?
I had some problems with 'widget inspector mode' but found a solution
https://github.com/Milad-Akarie/auto_route_library/issues/121#issuecomment-636308093

**Comment by slavap** [comment]
@vasilich6107 Unfortunately your solution is not working, getting the same error with Dart DevTools
Inspector "Select Widget Mode".

**Comment by slavap** [comment]
@nateshmbhat Could you please take a look at this issue. Supposedly it is quite simple one to fix, but will improve development process a lot.

**Comment by AlaaEldeenYsr** [comment]
@nateshmbhat Any updates here ? till now we can't use the latest version.

**Comment by slavap** [comment]
Still the same problem with 0.6.1 :-(
```code
Caught error: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2721 pos 14: 'observer.navigator == null': is not true.
I/flutter (26110): │ ⛔ #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
I/flutter (26110): │ ⛔ #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
I/flutter (26110): │ ⛔ #2      NavigatorState.initState (package:flutter/src/widgets/navigator.dart:2721:14)
I/flutter (26110): │ ⛔ #3      ExtendedNavigatorState.initState (package:auto_route/src/extended_navigator.dart:171:11)
I/flutter (26110): │ ⛔ #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
I/flutter (26110): │ ⛔ #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
I/flutter (26110): │ ⛔ #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
I/flutter (26110): │ ⛔ #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
I/flutter (26110): │ ⛔ #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter (26110): │ ⛔ #9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter (26110): │ ⛔ #10     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter (26110): │ ⛔ #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
I/flutter (26110): │ ⛔ #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
I/flutter (26110): │ ⛔ #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
I/flutter (26110): │ ⛔ #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
I/flutter (26110): │ ⛔ #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
I/flutter (26110): │ ⛔ #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter (26110): │ ⛔ #17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter (26110): │ ⛔ #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter (26110): │ ⛔ #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
I/flutter (26110): │ ⛔ #20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
I/flutter (26110): │ ⛔ #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
I/flutter (26110): │ ⛔ #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
I/flutter (26110): │ ⛔ #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
I/flutter (26110): │ ⛔ #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter (26110): │ ⛔ #25     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter (26110): │ ⛔ #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
I/flutter (26110): │ ⛔ #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
I/flutter (26110): │ ⛔ #28     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
I/flutter (26110): │ ⛔ #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
I/flutter (26110): │ ⛔ #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
I/flutter (26110): │ ⛔ #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
```

**Comment by Milad-Akarie** [comment]
Hey @slavap sorry for the delay I've been a bit busy lately. 
How can I reproduce this?

**Comment by slavap** [comment]
@Milad-Akarie Sorry for bothering. Reproduce steps is quite simple. Navigate to next page from initial, then call Flutter dev tools and press Inspector "Select Widget Mode" button.
![image](https://user-images.githubusercontent.com/4129763/86750660-f9133d80-bff2-11ea-8081-927b37caeef5.png)

**Comment by slavap** [comment]
@Milad-Akarie 
Now in 0.6.2 it is changed to the following error:
```
                     ⛔ Caught error: A GlobalKey was used multiple times inside one widget's child list.
I/flutter (27060): │ ⛔ The offending GlobalKey was: [GlobalObjectKey<NavigatorState> ExtendedNavigatorState<Router>#4c4e6]
I/flutter (27060): │ ⛔ The parent of the widgets with that key was:
I/flutter (27060): │ ⛔   ExtendedNavigator<Router>
I/flutter (27060): │ ⛔ The first child to get instantiated with that key became:
I/flutter (27060): │ ⛔   Navigator-[GlobalObjectKey<NavigatorState> ExtendedNavigatorState<Router>#4c4e6]
I/flutter (27060): │ ⛔ The second child that was to be instantiated with that key was:
I/flutter (27060): │ ⛔   ExtendedNavigator<Router>
I/flutter (27060): │ ⛔ A GlobalKey can only be specified on one widget at a time in the widget tree.
```

**Comment by Milad-Akarie** [comment]
@slavap I can't reproduce this but I think I know what might be the cause.

**Comment by slavap** [comment]
@Milad-Akarie And now in 0.6.5 it has stopped working completely for me :-( Just dies on app startup:
```
( 9665): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9665): The following assertion was thrown building ExtendedNavigator<Router>(state:
I/flutter ( 9665): ExtendedNavigatorState<Router>#98e50):
I/flutter ( 9665): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2725 pos 14:
I/flutter ( 9665): 'observer.navigator == null': is not true.
I/flutter ( 9665):
I/flutter ( 9665): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9665): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9665): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9665):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 9665):
I/flutter ( 9665): The relevant error-causing widget was:
I/flutter ( 9665):   ExtendedNavigator<Router>
I/flutter ( 9665):   
lib\app\themeable_app.dart:100
I/flutter ( 9665):
I/flutter ( 9665): When the exception was thrown, this was the stack:
I/flutter ( 9665): #2      NavigatorState.initState 
package:flutter/…/widgets/navigator.dart:2725
I/flutter ( 9665): #3      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4684
I/flutter ( 9665): #4      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4520
I/flutter ( 9665): #5      Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3490
I/flutter ( 9665): #6      Element.updateChild 
package:flutter/…/widgets/framework.dart:3255
I/flutter ( 9665): #7      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 9665): #8      StatefulElement.performRebuild 
package:flutter/…/widgets/framework.dart:4719
I/flutter ( 9665): #9      Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 9665): #10     StatefulElement.update 
package:flutter/…/widgets/framework.dart:4751
I/flutter ( 9665): #11     Element.updateChild 
package:flutter/…/widgets/framework.dart:3245
I/flutter ( 9665): #12     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 9665): #13     StatefulElement.performRebuild 
package:flutter/…/widgets/framework.dart:4719
I/flutter ( 9665): #14     Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 9665): #15     BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2667
I/flutter ( 9665): #16     WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:866
I/flutter ( 9665): #17     RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:286
I/flutter ( 9665): #18     SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1117
I/flutter ( 9665): #19     SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1056
I/flutter ( 9665): #20     SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:972
I/flutter ( 9665): #24     _invoke  (dart:ui/hooks.dart:253:10)
I/flutter ( 9665): #25     _drawFrame  (dart:ui/hooks.dart:211:3)
```

**Comment by slavap** [comment]
@Milad-Akarie Reverting back to 
auto_route: ^0.6.2
auto_route_generator: ^0.6.3
without any other code changes is fixing previous error with 0.6.5 completely.

**Comment by slavap** [comment]
@Milad-Akarie Updated to 0.6.6
Now everything seems to be working, and "Select Widget Mode" ! Thank you!
With this change from doc:
```dart
 // builder uses the native nav key to keep
      // the state of ExtendedNavigator so it won't reload
      // when using Flutter tools-> select widget mode
     builder: ExtendedNavigator.builder<Router>(router: Router(),
     // pass anything navigation related to ExtendedNav instead of MaterialApp
         initialRoute: ...
         observers:...
         navigatorKey:...
         onUnknownRoute:...
     ),
```

**Comment by Milad-Akarie** [comment]
@slavap That's what I did at the begining then I thought invoking a function at the end of  another function 
`builder(..)(ctx,child)` might scare some people off lol

**Comment by Milad-Akarie** [comment]
so I guess I should close this for now.
