### ISSUE TITLE
stack router inside tabs router not working

### ISSUE THREAD

**Issue by watertcm** [Milad-Akarie/auto_route_library#1090]
hello
I am trying to create a stack in a tabs router
but i get this error when clicking on settings tab and click the next button on top left

below is my sample code , it is very short
[lib.zip](https://github.com/Milad-Akarie/auto_route_library/files/8818359/lib.zip)

error is:
Looks like you're trying to navigate to a nested route without adding their   
parent to stack first
try navigating to MainRoute -> ThirdPageRoute -> ForthPageRoute
    at Object.throw_ [as throw] (http://localhost:64764/dart_sdk.js:5080:11)  
    at [_matchOrReportFailure]
    (http://localhost:64764/packages/auto_route/src/router/widgets/wrapped_rou    te.dart.lib.js:4092:21)
    at router$46gr.AppRouter.new._navigate
    (http://localhost:64764/packages/auto_route/src/router/widgets/wrapped_rou    te.dart.lib.js:4140:48)
    at _navigate.next (<anonymous>)
    at runBody (http://localhost:64764/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:64764/dart_sdk.js:40691:7)  
    at [_navigate]
    (http://localhost:64764/packages/auto_route/src/router/widgets/wrapped_rou    te.dart.lib.js:4139:20)
    at router$46gr.AppRouter.new.navigate
    (http://localhost:64764/packages/auto_route/src/router/widgets/wrapped_rou    te.dart.lib.js:4134:88)
    at navigate.next (<anonymous>)
    at runBody (http://localhost:64764/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:64764/dart_sdk.js:40691:7)  
    at router$46gr.AppRouter.new.navigate
    (http://localhost:64764/packages/auto_route/src/router/widgets/wrapped_rou    te.dart.lib.js:4133:20)
    at http://localhost:64764/packages/tabsrouter/router.gr.dart.lib.js:890:62    at [_handleTap]
    (http://localhost:64764/packages/flutter/src/material/icon_button.dart.lib    .js:42247:31)
    at tap.TapGestureRecognizer.new.invokeCallback
    (http://localhost:64764/packages/flutter/src/gestures/recognizer.dart.lib.    js:198:18)
    at tap.TapGestureRecognizer.new.handleTapUp
    (http://localhost:64764/packages/flutter/src/gestures/tap.dart.lib.js:411:    42)
    at [_checkUp]
    (http://localhost:64764/packages/flutter/src/gestures/tap.dart.lib.js:217:    12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer
    (http://localhost:64764/packages/flutter/src/gestures/tap.dart.lib.js:166:    23)
    at tap.TapGestureRecognizer.new.handleEvent
    (http://localhost:64764/packages/flutter/src/gestures/recognizer.dart.lib.    js:444:16)
    at [_dispatch]
    (http://localhost:64764/packages/flutter/src/gestures/pointer_router.dart.    lib.js:86:9)
    at
    http://localhost:64764/packages/flutter/src/gestures/pointer_router.dart.l    ib.js:112:26
    at LinkedMap.new.forEach (http://localhost:64764/dart_sdk.js:27745:11)    
    at [_dispatchEventToRoutes]
    (http://localhost:64764/packages/flutter/src/gestures/pointer_router.dart.    lib.js:110:29)
    at pointer_router.PointerRouter.new.route
    (http://localhost:64764/packages/flutter/src/gestures/pointer_router.dart.    lib.js:105:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent
    (http://localhost:64764/packages/flutter/src/gestures/binding.dart.lib.js:    367:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent
    (http://localhost:64764/packages/flutter/src/gestures/binding.dart.lib.js:    355:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent
    (http://localhost:64764/packages/flutter/src/rendering/layer.dart.lib.js:5    440:13)
    at [_handlePointerEventImmediately]
    (http://localhost:64764/packages/flutter/src/gestures/binding.dart.lib.js:    331:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent
    (http://localhost:64764/packages/flutter/src/gestures/binding.dart.lib.js:    305:43)
    at [_flushPointerEventQueue]
    (http://localhost:64764/packages/flutter/src/gestures/binding.dart.lib.js:    295:14)
    at [_handlePointerDataPacket]
    (http://localhost:64764/packages/flutter/src/gestures/binding.dart.lib.js:    286:54)
    at Object.invoke1 (http://localhost:64764/dart_sdk.js:191747:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket
    (http://localhost:64764/dart_sdk.js:171943:15)
    at [_onPointerData] (http://localhost:64764/dart_sdk.js:172879:49)        
    at http://localhost:64764/dart_sdk.js:173317:28
    at http://localhost:64764/dart_sdk.js:173273:16
    at loggedHandler (http://localhost:64764/dart_sdk.js:172978:11)

**Comment by watertcm** [comment]
yeah i know hats wrong my bad
