### ISSUE TITLE
RouteArgs can not be null because it has a required parameter after web app resize.

### ISSUE THREAD

**Issue by Turbozanik** [Milad-Akarie/auto_route_library#1146]
### Error: 
I am receiving `Error: SelectGameDifficultyRouteArgs can not be null because it has a required parameter` after web app browser window resize.

I am sure that args are not null, as I am printing them out in the log.

It might be reated to flutter3, as I was testing this a while ago and it worked. But it isn't working now.

Any ideas on what may cause this and how can I fix it?

### How do I pass parameters:

```
class HomeAutoRoutePage extends StatelessWidget {
  @override
  Widget build(context) {
    return AutoTabsScaffold(
        backgroundColor: QuizTimeColors.background_purple,
        routes: [
          GAME_ROUTER(children: [ // this is added to be able to pass bloc in a DI fashion, instead of a service locator
            SelectGameDifficultyRoute(
                bloc: DiContainer.instance.getOrCreateSelectDifficultyInjector().get<SelectDifficultyPageBloc>())
          ]),
          PROFILE_ROUTER(),
        ],
        bottomNavigationBuilder: (_, tabsRouter) {
          return WillPopScope(
            onWillPop: () {
              if (tabsRouter.activeIndex == 0) {
                // app will be closed
                return Future.value(true);
              }

              // we will switch to previous tab
              tabsRouter.setActiveIndex(tabsRouter.activeIndex - 1);
              return Future.value(false);
            },
            child: BottomNavigationBar(
              backgroundColor: Colors.blue,
              type: BottomNavigationBarType.fixed,
              selectedItemColor: Colors.white,
              unselectedItemColor: Colors.black,
              currentIndex: tabsRouter.activeIndex,
              onTap: tabsRouter.setActiveIndex,
              items: [
                BottomNavigationBarItem(label: LocaleKeys.common_game_tab.tr(), icon: Icon(Icons.videogame_asset)),
                BottomNavigationBarItem(label: LocaleKeys.common_profile_tab_title.tr(), icon: Icon(Icons.person)),
              ],
            ),
          );
        });
  }
}
```
### My router setup

```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    // the empty router widget has an AutoRouter widget to render child routes
    AutoRoute(path: '/', page: EmptyRouterWidget, children: [
      AutoRoute(path: '', page: SplashPage), // auto_route will treat this as initial page since it has an empty path
      AutoRoute(path: 'login', page: LoginPage),
      AutoRoute(path: 'home', page: HomeAutoRoutePage, children: [
        AutoRoute(
          path: 'difficulty',
          name: GAME_ROUTER,
          page: EmptyRouterPage,
          children: [
            AutoRoute(path: '', page: SelectGameDifficultyPage),
            AutoRoute(path: 'topic', page: GameTopicPage),
            AutoRoute(path: 'question_topic_set', page: QuestionSetPage),
          ],
        ),
        AutoRoute(
          path: 'profile',
          name: PROFILE_ROUTER,
          page: EmptyRouterPage,
          children: [AutoRoute(path: '', page: ProfilePage)],
        )
      ]),
      AutoRoute(path: 'game', page: GamePage),
      AutoRoute(path: "game_finished", page: GameFinishedPage)
    ])
  ],
)
class $AppRouter {}

class EmptyRouterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AutoRouter();
  }
}
```

### Full error log:

```
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 421ms.
2022-07-06T15:20:52.681	E	Flutter:	 ============================  default **<- This is the name of my di container, that holds the SelectGameDifficultyRouteArgs value.**
[🌎 Easy Localization] [DEBUG] Localization initialized
[🌎 Easy Localization] [DEBUG] Start
[🌎 Easy Localization] [DEBUG] Init state
[🌎 Easy Localization] [DEBUG] Build
[🌎 Easy Localization] [DEBUG] Init Localization Delegate
[🌎 Easy Localization] [DEBUG] Init provider
[🌎 Easy Localization] [DEBUG] Load Localization Delegate
2022-07-06T15:20:58.241	E	Flutter:	 Instance of 'SelectDifficultyPageBloc' **<- This is the SelectGameDifficultyRouteArgs  value itself**
Error: SelectGameDifficultyRouteArgs can not be null because it has a required parameter
    at Object.throw_ [as throw] (http://localhost:50075/dart_sdk.js:5080:11)
    at routing_controller.RouteData.new.argsAs (http://localhost:50075/packages/auto_route/src/router/widgets/wrapped_route.dart.lib.js:5461:21)
    at http://localhost:50075/packages/quiz_time/navigation/auto_router/quiz_time_router.dart.lib.js:6571:30
    at [_pageBuilder] (http://localhost:50075/packages/auto_route/src/router/widgets/wrapped_route.dart.lib.js:6655:70)
    at [_addEntry] (http://localhost:50075/packages/auto_route/src/router/widgets/wrapped_route.dart.lib.js:5008:35)
    at routing_controller.NestedStackRouter.new._pushAllGuarded (http://localhost:50075/packages/auto_route/src/router/widgets/wrapped_route.dart.lib.js:4992:46)
    at _pushAllGuarded.next (<anonymous>)
    at http://localhost:50075/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:50075/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50075/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:50075/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:50075/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:50075/dart_sdk.js:35872:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50075/dart_sdk.js:35906:35)
    at Object._microtaskLoop (http://localhost:50075/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:50075/dart_sdk.js:40784:13)
    at http://localhost:50075/dart_sdk.js:36261:9
[🌎 Easy Localization] [DEBUG] Build
[🌎 Easy Localization] [DEBUG] Init Localization Delegate
[🌎 Easy Localization] [DEBUG] Init provider

```
**Flutter doctor -v**

```
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.18363.719])
    • Flutter version 3.0.4 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (6 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\*\AppData\Local\Android\sdk
    • Platform android-31, build-tools 32.0.0
    • ANDROID_HOME = C:\Users\*\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.719]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114

[√] HTTP Host Availability
    • All required HTTP hosts are available

```

**Comment by shtreb** [comment]
Why it is closed? Problem is actual wih AutoTabsRouter
