### ISSUE TITLE
Auto route in nested app 

### ISSUE THREAD

**Issue by yeras-is** [Milad-Akarie/auto_route_library#1160]
Hi folks, I have one parent app with Navigator 1, and one child App with AutoRoute as navigation. When I'm trying to pass navigatorKey from Parent to Child app and set it on AppRouter I receive error like down below. How can I pass navigator key and have one navigation stack between two apps ?

```dart
Restarted application in 226ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building AutoRouteNavigator(dependencies: [_LocalizationsScope-[GlobalKey#b59f2], _InheritedTheme], state: _AutoRouteNavigatorState#f64cb):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1931 pos 12: 'element._lifecycleState == _ElementLifecycle.active': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      _InactiveElements._deactivateRecursively
#3      ComponentElement.visitChildren
#4      _InactiveElements._deactivateRecursively
#5      ComponentElement.visitChildren
#6      _InactiveElements._deactivateRecursively
#7      ComponentElement.visitChildren
#8      _InactiveElements._deactivateRecursively
#9      ComponentElement.visitChildren
#10     _InactiveElements._deactivateRecursively
#11     ComponentElement.visitChildren
#12     _InactiveElements._deactivateRecursively
#13     ComponentElement.visitChildren
#14     _InactiveElements._deactivateRecursively
#15     ComponentElement.visitChildren
#16     _InactiveElements._deactivateRecursively
#17     ComponentElement.visitChildren
#18     _InactiveElements._deactivateRecursively
#19     ComponentElement.visitChildren
#20     _InactiveElements._deactivateRecursively
#21     ComponentElement.visitChildren
#22     _InactiveElements._deactivateRecursively
#23     ComponentElement.visitChildren
#24     _InactiveElements._deactivateRecursively
#25     ComponentElement.visitChildren
#26     _InactiveElements._deactivateRecursively
#27     ComponentElement.visitChildren
#28     _InactiveElements._deactivateRecursively
#29     ComponentElement.visitChildren
#30     _InactiveElements._deactivateRecursively
#31     ComponentElement.visitChildren
#32     _InactiveElements._deactivateRecursively
#33     ComponentElement.visitChildren
#34     _InactiveElements._deactivateRecursively
#35     ComponentElement.visitChildren
#36     _InactiveElements._deactivateRecursively
#37     ComponentElement.visitChildren
#38     _InactiveElements._deactivateRecursively
#39     ComponentElement.visitChildren
#40     _InactiveElements._deactivateRecursively
#41     SingleChildRenderObjectElement.visitChildren
#42     _InactiveElements._deactivateRecursively
#43     ComponentElement.visitChildren
#44     _InactiveElements._deactivateRecursively
#45     ComponentElement.visitChildren
#46     _InactiveElements._deactivateRecursively
#47     ComponentElement.visitChildren
#48     _InactiveElements._deactivateRecursively
#49     ComponentElement.visitChildren
#50     _InactiveElements._deactivateRecursively
#51     ComponentElement.visitChildren
#52     _InactiveElements._deactivateRecursively
#53     SingleChildRenderObjectElement.visitChildren
#54     _InactiveElements._deactivateRecursively
#55     ComponentElement.visitChildren
#56     _InactiveElements._deactivateRecursively
#57     ComponentElement.visitChildren
#58     _InactiveElements._deactivateRecursively
#59     ComponentElement.visitChildren
#60     _InactiveElements._deactivateRecursively
#61     ComponentElement.visitChildren
#62     _InactiveElements._deactivateRecursively
#63     ComponentElement.visitChildren
#64     _InactiveElements._deactivateRecursively
#65     ComponentElement.visitChildren
#66     _InactiveElements._deactivateRecursively
#67     ComponentElement.visitChildren
#68     _InactiveElements._deactivateRecursively
#69     ComponentElement.visitChildren
#70     _InactiveElements._deactivateRecursively
#71     ComponentElement.visitChildren
#72     _InactiveElements._deactivateRecursively
#73     ComponentElement.visitChildren
#74     _InactiveElements._deactivateRecursively
#75     SingleChildRenderObjectElement.visitChildren
#76     _InactiveElements._deactivateRecursively
#77     ComponentElement.visitChildren
#78     _InactiveElements._deactivateRecursively
#79     ComponentElement.visitChildren
#80     _InactiveElements._deactivateRecursively
#81     ComponentElement.visitChildren
#82     _InactiveElements._deactivateRecursively
#83     ComponentElement.visitChildren
#84     _InactiveElements._deactivateRecursively
#85     SingleChildRenderObjectElement.visitChildren
#86     _InactiveElements._deactivateRecursively
#87     ComponentElement.visitChildren
#88     _InactiveElements._deactivateRecursively
#89     ComponentElement.visitChildren
#90     _InactiveElements._deactivateRecursively
#91     ComponentElement.visitChildren
#92     _InactiveElements._deactivateRecursively
#93     ComponentElement.visitChildren
#94     _InactiveElements._deactivateRecursively
#95     ComponentElement.visitChildren
#96     _InactiveElements._deactivateRecursively
#97     ComponentElement.visitChildren
#98     _InactiveElements._deactivateRecursively
#99     ComponentElement.visitChildren
#100    _InactiveElements._deactivateRecursively
#101    ComponentElement.visitChildren
#102    _InactiveElements._deactivateRecursively
#103    ComponentElement.visitChildren
#104    _InactiveElements._deactivateRecursively
#105    ComponentElement.visitChildren
#106    _InactiveElements._deactivateRecursively
#107    SingleChildRenderObjectElement.visitChildren
#108    _InactiveElements._deactivateRecursively
#109    ComponentElement.visitChildren
#110    _InactiveElements._deactivateRecursively
#111    ComponentElement.visitChildren
#112    _InactiveElements._deactivateRecursively
#113    ComponentElement.visitChildren
#114    _InactiveElements._deactivateRecursively
#115    ComponentElement.visitChildren
#116    _InactiveElements._deactivateRecursively
#117    ComponentElement.visitChildren
#118    _InactiveElements._deactivateRecursively
#119    ComponentElement.visitChildren
#120    _InactiveElements._deactivateRecursively
#121    SingleChildRenderObjectElement.visitChildren
#122    _InactiveElements._deactivateRecursively
#123    ComponentElement.visitChildren
#124    _InactiveElements._deactivateRecursively
#125    SingleChildRenderObjectElement.visitChildren
#126    _InactiveElements._deactivateRecursively
#127    SingleChildRenderObjectElement.visitChildren
#128    _InactiveElements._deactivateRecursively
#129    ComponentElement.visitChildren
#130    _InactiveElements._deactivateRecursively
#131    MultiChildRenderObjectElement.visitChildren
#132    _InactiveElements._deactivateRecursively
#133    ComponentElement.visitChildren
#134    _InactiveElements._deactivateRecursively
#135    SingleChildRenderObjectElement.visitChildren
#136    _InactiveElements._deactivateRecursively
#137    ComponentElement.visitChildren
#138    _InactiveElements._deactivateRecursively
#139    SingleChildRenderObjectElement.visitChildren
#140    _InactiveElements._deactivateRecursively
#141    ComponentElement.visitChildren
#142    _InactiveElements._deactivateRecursively
#143    SingleChildRenderObjectElement.visitChildren
#144    _InactiveElements._deactivateRecursively
#145    ComponentElement.visitChildren
#146    _InactiveElements._deactivateRecursively
#147    ComponentElement.visitChildren
#148    _InactiveElements._deactivateRecursively
#149    ComponentElement.visitChildren
#150    _InactiveElements._deactivateRecursively
#151    SingleChildRenderObjectElement.visitChildren
#152    _InactiveElements._deactivateRecursively
#153    SingleChildRenderObjectElement.visitChildren
#154    _InactiveElements._deactivateRecursively
#155    ComponentElement.visitChildren
#156    _InactiveElements._deactivateRecursively
#157    SingleChildRenderObjectElement.visitChildren
#158    _InactiveElements._deactivateRecursively
#159    ComponentElement.visitChildren
#160    _InactiveElements._deactivateRecursively
#161    ComponentElement.visitChildren
#162    _InactiveElements._deactivateRecursively
#163    ComponentElement.visitChildren
#164    _InactiveElements._deactivateRecursively
#165    ComponentElement.visitChildren
#166    _InactiveElements._deactivateRecursively
#167    ComponentElement.visitChildren
#168    _InactiveElements._deactivateRecursively
#169    ComponentElement.visitChildren
#170    _InactiveElements._deactivateRecursively
#171    SingleChildRenderObjectElement.visitChildren
#172    _InactiveElements._deactivateRecursively
#173    ComponentElement.visitChildren
#174    _InactiveElements._deactivateRecursively
#175    ComponentElement.visitChildren
#176    _InactiveElements._deactivateRecursively
#177    ComponentElement.visitChildren
#178    _InactiveElements._deactivateRecursively
#179    ComponentElement.visitChildren
#180    _InactiveElements._deactivateRecursively
#181    ComponentElement.visitChildren
#182    _InactiveElements._deactivateRecursively
#183    SingleChildRenderObjectElement.visitChildren
#184    _InactiveElements._deactivateRecursively
#185    ComponentElement.visitChildren
#186    _InactiveElements._deactivateRecursively
#187    ComponentElement.visitChildren
#188    _InactiveElements._deactivateRecursively
#189    ComponentElement.visitChildren
#190    _InactiveElements._deactivateRecursively
#191    MultiChildRenderObjectElement.visitChildren
#192    _InactiveElements._deactivateRecursively
#193    ComponentElement.visitChildren
#194    _InactiveElements._deactivateRecursively
#195    ComponentElement.visitChildren
#196    _InactiveElements._deactivateRecursively
#197    ComponentElement.visitChildren
#198    _InactiveElements._deactivateRecursively
#199    SingleChildRenderObjectElement.visitChildren
#200    _InactiveElements._deactivateRecursively
#201    ComponentElement.visitChildren
#202    _InactiveElements._deactivateRecursively
#203    SingleChildRenderObjectElement.visitChildren
#204    _InactiveElements._deactivateRecursively
#205    SingleChildRenderObjectElement.visitChildren
#206    _InactiveElements._deactivateRecursively
#207    ComponentElement.visitChildren
#208    _InactiveElements._deactivateRecursively
#209    ComponentElement.visitChildren
#210    _InactiveElements._deactivateRecursively
#211    _InactiveElements.add
#212    Element.deactivateChild
#213    Element._retakeInactiveElement
#214    Element.inflateWidget
#215    Element.updateChild
#216    ComponentElement.performRebuild
#217    StatefulElement.performRebuild
#218    Element.rebuild
#219    StatefulElement.update
#220    Element.updateChild
#221    ComponentElement.performRebuild
#222    Element.rebuild
#223    ProxyElement.update
#224    Element.updateChild
#225    ComponentElement.performRebuild
#226    Element.rebuild
#227    ProxyElement.update
#228    Element.updateChild
#229    ComponentElement.performRebuild
#230    StatefulElement.performRebuild
#231    Element.rebuild
#232    StatefulElement.update
#233    Element.updateChild
#234    ComponentElement.performRebuild
#235    Element.rebuild
#236    StatelessElement.update
#237    Element.updateChild
#238    ComponentElement.performRebuild
#239    Element.rebuild
#240    ProxyElement.update
#241    Element.updateChild
#242    ComponentElement.performRebuild
#243    Element.rebuild
#244    ProxyElement.update
#245    Element.updateChild
#246    ComponentElement.performRebuild
#247    StatefulElement.performRebuild
#248    Element.rebuild
#249    BuildOwner.buildScope
#250    WidgetsBinding.drawFrame
#251    RendererBinding._handlePersistentFrameCallback
#252    SchedulerBinding._invokeFrameCallback
#253    SchedulerBinding.handleDrawFrame
#254    SchedulerBinding._handleDrawFrame
#258    _invoke (dart:ui/hooks.dart:151:10)
#259    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#260    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3590 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3590 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3590 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3590 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3590 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3590 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3590 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3590 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Duplicate GlobalKey detected in widget tree.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget inspector ══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

```

**Comment by yeras-is** [comment]
as two apps I mean two apps with independent MaterialApp and routing, I have experience in combining apps with Navigator 1, but Idk how to deal with AutoRoute. I've tried to create constructor for AppRouter and pass NavigatorKey but It trows error 
```
class MarketAppRouter extends _$MarketAppRouter {
  MarketAppRouter([GlobalKey<NavigatorState>? navigatorKey]) : super(navigatorKey);
}
```
