### ISSUE TITLE
nested autorouter / [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Can not navigate to MainPage #0      RoutingController._findPathScopeOrReportFailure

### ISSUE THREAD

**Issue by Sully55** [Milad-Akarie/auto_route_library#1210]
I'm using a custom bottom navigation bar and I want to navigate between my pages, so I used the auto_route package.

After the splash screen launches, my app screen turns white and I get this error

```
 Launching lib/main.dart on iPhone 13 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           64.2s
Debug service listening on ws://127.0.0.1:55355/joEDYrkJRvA=/ws
Syncing files to device iPhone 13 Pro Max...
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Can not navigate to MainPage
#0      RoutingController._findPathScopeOrReportFailure (package:auto_route/src/router/controller/routing_controller.dart:182:7)
#1      StackRouter.pushNamed (package:auto_route/src/router/controller/routing_controller.dart:1196:19)
#2      _SplashPageState.initState.<anonymous closure> (package:emart/pages/splash_page.dart:23:28)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12) `
```

This is my Route page

```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Router',
  routes: [
    AutoRoute(
        path: '/',
        page: SplashPage,
        initial: true,
        children: [
          // Main Page
          AutoRoute(
         path: 'auth',
            name: 'MainPageRouter',
            page: EmptyRouterPage,
          ),
          // Home Page
          AutoRoute(
            path: 'pages',
            name: 'HomeRouter',initial: true,
            page: EmptyRouterPage,
            children: [
              AutoRoute(path: 'pages', page: HomePage,
              ),
            ],
          ),
          //Brands Page
          AutoRoute(
            path: 'pages',
            name: 'BrandsRouter',
            page: EmptyRouterPage,
            children: [
              AutoRoute(path: 'pages', page: BrandsPage,
              ),
            ],
          ),
          //  ProfileBody
          AutoRoute(
              path: 'pages/profile',
              name: 'UsersRouter',
              page: EmptyRouterPage,
              children: [
                AutoRoute(
                  path: 'profile',
                  page:ProfileBody,
                ),
                AutoRoute(
                  path: 'profile',
                  page:AccountPageInfo,
                ),
                AutoRoute(
                  path: 'profile',
                  page:CridetCardPage,
                ),
              ]
          ),
        ]),
  ],
)

class $AppRouter {}
```

Are there any mistakes in the way that I did the routing?

and this is my splash screen

```
class SplashPage extends StatefulWidget {
  const SplashPage({Key? key}) : super(key: key);

  @override
  State<SplashPage> createState() => _SplashPageState();
}

class _SplashPageState extends State<SplashPage> {

  //After 3 Seconds load login page
  Timer? _timer;
  @override
  void initState() {
    _timer = Timer(const Duration(seconds: 3),() =>

    AutoRouter.of(context).pushNamed('MainPage'),
    );
    super.initState();
  }

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    return Center(
        child: Image.asset("assets/splash.gif",
          // fit: BoxFit.fill,
        )

    );
  }
}

```
and this is the main page 

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}


class _MyAppState extends State<MyApp> {


  @override
  Widget build(BuildContext context) {

    final _appRouter = AppRouter();
    return GestureDetector(
      onTap: () => FocusScope.of(context).unfocus(),
      child: ChangeNotifierProvider(
        create: (context) => GoogleSignInProvider(),
        child: MaterialApp.router(
          debugShowCheckedModeBanner: false,
          title: '',
          routerDelegate: _appRouter.delegate(),
          routeInformationParser: _appRouter.defaultRouteParser(),
          // theme: lightTheme,
          // darkTheme: darkTheme,
          // themeMode: _themeManager.themeMode,
        ),
      ),
    );
  }
}`
```

and this is my homepage 

```
`class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

int _selectedItem = 0;
final List pages = [
  MainPage(),
  HomePage(),
  BrandsPage(
    onClickedItem: (item) {
      final snackBar = SnackBar(
        content: Text(
          'Clicked Item $item',
          style: const TextStyle(fontSize: 20),
        ),
      );
    },
    items: const ['ATest', 'BTest', 'CTest','MTest', 'KTest'],
  ),
  ProfileBody(),
];

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return AutoTabsScaffold(
      appBarBuilder: (_, tabsRouter) => AppBar(
        backgroundColor: AppTheme.colors.Light,
        title: const Text('FlutterBottomNav'),
        centerTitle: true,
        leading: const AutoLeadingButton(
          color: Colors.deepPurpleAccent,
        ),
      ),
      // backgroundColor: AppTheme.colors.Light,
      routes: [
        MainPageRouter(),
        HomeRouter(),
        BrandsRouter(
          onClickedItem: (item) {
            final snackBar = SnackBar(
              content: Text(
                'Clicked Item $item',
                style: const TextStyle(fontSize: 20),
              ),
            );
          },
          items: const ['Sally', 'Faers', 'Test'],
        ),
        UsersRouter(),
      ],
      bottomNavigationBuilder: _selectedItem == 0
          ? null
          : (_, tabsRouter) {
              return SingleChildScrollView(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    CustomBottonNavigationBar(
                      iconList: const [
                        Icons.home,
                        Icons.card_giftcard,
                        Icons.document_scanner_outlined,
                        Icons.pie_chart,
                        Icons.person,
                      ],
                      onChange: (val) {
                        setState(() {
                          _selectedItem = val;
                        });
                      },
                      defaultSelectedIndex: 0,
                    ),
                    BannerScroll(),
                    const SizedBox(
                      height: (20.0),
                    ),
                    newArraival(),
                    const ProductsFrame(),
                    featuredBrands(),
                    const SizedBox(
                      height: (20.0),
                    ),
                    Carousel(),
                    const SizedBox(
                      height: (20.0),
                    ),
                    newArraival(),
                    const ProductsFrame(),
                  ],
                ),
              );
            },
    );
  }
}`
```

**Comment by kmrosiek** [comment]
Try to add one screen with tab navigation:
```
class TabNavigationScreen extends StatelessWidget {
  const TabNavigationScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return AutoTabsScaffold(
      animationDuration: const Duration(milliseconds: 0),
      routes: const [
        MainPageRouter(),
        HomeRouter(),
        BrandsRouter()
        UsersRouter(),
      ],
      bottomNavigationBuilder: (_, tabsRouter) {
        return BottomNavigationBar(
          currentIndex: tabsRouter.activeIndex,
          onTap: tabsRouter.setActiveIndex,
          items: const [
            BottomNavigationBarItem(label: 'Main'),
            BottomNavigationBarItem(label: 'Home'),
            BottomNavigationBarItem(label: 'Brands'),
            BottomNavigationBarItem(label: 'Users'),
          ],
        );
      },
    );
  }
}

```

Then from `splashScreen` you navigate to `TabNavigationRouter` instead of `MainPage`.
Your router page could look like this:

```
AutoRoute(page: TabNavigationScreen, children: [
      AutoRoute(page: MainPageScreen),
      AutoRoute(page: HomeScreen),
      AutoRoute(page: BrandsScreen),
      AutoRoute(page: UsersScreen),
    ]),

```
