### ISSUE TITLE
AutoTabsRouter operation requested with a context that does not include an AutoTabsRouter.

### ISSUE THREAD

**Issue by mrqaidi** [Milad-Akarie/auto_route_library#1243]
Hi

i am getting this error on app start   dont know what cause this   

full error

```
`
I/flutter ( 7443): ┌─────────────────────────────────────────────────
I/flutter ( 7443): │ AutoTabsRouter operation requested with a context that does not include an AutoTabsRouter.
I/flutter ( 7443): │ The context used to retrieve the AutoTabsRouter must be that of a widget that is a descendant of an AutoTabsRouter widget.
I/flutter ( 7443): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 7443): │ #0   AutoTabsRouter.of.<anonymous closure> (package:auto_route/src/router/widgets/auto_tabs_router.dart:91:9)
I/flutter ( 7443): │ #1   AutoTabsRouter.of (package:auto_route/src/router/widgets/auto_tabs_router.dart:97:6)
`
```

**Comment by Tetsukick** [comment]
same issue with me
