### ISSUE TITLE
Unhandled Exception: Expected [ArticleScreenArgs],  found [ArticleScreenArgs]

### ISSUE THREAD

**Issue by aly22** [Milad-Akarie/auto_route_library#1315]
I am trying to pass arguments from one page to another, and I'm getting the following error:
Apparently, the hashcodes don't match for T and args.

hashCodeForT: 696241111
hashCodeForArgs: 114336981
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Expected [ArticleScreenArgs],  found [ArticleScreenArgs]
#0      RouteData.argsAs (package:auto_route/src/route/route_data.dart:44:7)
#1      new AppRouter.<anonymous closure> (package:qubit/router/app_router.gr.dart%20%20%20%20%20%20%20%20%20%20%20:36:30)
#2      RootStackRouter._pageBuilder (package:auto_route/src/router/controller/root_stack_router.dart:102:20)
#3      StackRouter._addEntry (package:auto_route/src/router/controller/routing_controller.dart:1132:29)
#4      StackRouter._push (package:auto_route/src/router/controller/routing_controller.dart:952:14)
<asynchronous suspension>

Here is the relevant code:

```
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:qubit/classes/article.dart';
import 'package:qubit/router/app_router.gr.dart';

class HeadlineText extends StatelessWidget {
  const HeadlineText({Key? key, required this.textData}) : super(key: key);
  final String textData;
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => context.router.push(
        ArticleScreen(
          // articleDate: Article.articleDate,
          articleTitle:
              'String',
          // articleText: Article.articleText,
          // authorName: Article.authorName,
          // articleCategory: Article.articleCategory,
        ),
      ),
      child: Padding(
        padding: const EdgeInsets.only(right: 10.0),
        child: Text(
          textData,
          style: TextStyle(
            fontFamily: 'Roboto',
            color: Color(0xffa562fe),
          ),
        ),
      ),
    );
  }
}
```

```
import 'package:auto_route/auto_route.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:qubit/components/app_bar_of_app.dart';
import 'package:qubit/components/headline_text_list_view.dart';
import 'package:qubit/constants.dart';
import 'package:qubit/router/app_router.gr.dart';

class ArticleScreen extends StatelessWidget {
  final String articleTitle;
  const ArticleScreen({
    Key? key,
    // required this.articleCategory,
    required this.articleTitle,
    // required this.articleText,
    // required this.authorName,
    // required this.articleDate,
  }) : super(key: key);

  // final String articleText;
  // final String authorName;
  // final String articleCategory;
  // final String articleDate;

  @override
  Widget build(BuildContext context) {
    print('articlescreen got called.');
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(
            horizontal: 20,
          ),
          child: Column(
            children: [
              AppBarOfApp(),
              HeadlineTextListView(),
              TitleTextContainer(
                titleText: articleTitle,
              ),
```
and my app_router.gr.dart:

```
class AppRouter extends _i6.RootStackRouter {
  AppRouter([_i7.GlobalKey<_i7.NavigatorState>? navigatorKey])
      : super(navigatorKey);

  @override
  final Map<String, _i6.PageFactory> pagesMap = {
    HomeScreen.name: (routeData) {
      return _i6.MaterialPageX<dynamic>(
        routeData: routeData,
        child: _i1.HomeScreen(),
      );
    },
    ArticleScreen.name: (routeData) {
      final args = routeData.argsAs<ArticleScreenArgs>();
      return _i6.MaterialPageX<dynamic>(
        routeData: routeData,
        child: _i2.ArticleScreen(
          key: args.key,
          articleTitle: args.articleTitle,
        ),
      );
    },


/// generated route for
/// [_i2.ArticleScreen]
class ArticleScreen extends _i6.PageRouteInfo<ArticleScreenArgs> {
  ArticleScreen({
    _i7.Key? key,
    required String articleTitle,
  }) : super(
          ArticleScreen.name,
          path: '/article-screen',
          args: ArticleScreenArgs(
            key: key,
            articleTitle: articleTitle,
          ),
        );

  static const String name = 'ArticleScreen';
}

class ArticleScreenArgs {
  const ArticleScreenArgs({
    this.key,
    required this.articleTitle,
  });

  final _i7.Key? key;

  final String articleTitle;

  @override
  String toString() {
    return 'ArticleScreenArgs{key: $key, articleTitle: $articleTitle}';
  }
}
```

**Comment by aly22** [comment]
@Milad-Akarie

**Comment by Milad-Akarie** [comment]
@aly22 That's a weird one, can you please share the router setup? 
are you maybe declaring the same page more than ones?

**Comment by aly22** [comment]
> @aly22 That's a weird one, can you please share the router setup? are you maybe declaring the same page more than ones?

```
import 'package:auto_route/auto_route.dart';
import 'package:qubit/screens/article_screen.dart';
import 'package:qubit/screens/author_screen.dart';
import 'package:qubit/screens/category_screen.dart';
import 'package:qubit/screens/donation_screen.dart';
import 'package:qubit/screens/home_screen.dart';

@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(page: HomeScreen, initial: true),
    AutoRoute(page: ArticleScreen),
    AutoRoute(page: CategoryScreen),
    AutoRoute(page: AuthorScreen),
    AutoRoute(page: DonationScreen)
  ],
)
class $AppRouter {}
```

**Comment by DevNico** [comment]
This issue happens to me when using an Args class from a router module from another package.

**Comment by SirusCodes** [comment]
Any solution to this?

**Comment by guyluz11** [comment]
Just had the same problem, and found my fix!.

While moving rout folders I have exedently introduced `//` in the middle of the path to `app_router.gr.dart` in `app_router.dart` file.
So 
Bad:
`import 'package:cybear_jinni/presentation/core//routes/app_router.gr.dart';`
Good:
import 'package:cybear_jinni/presentation/core/routes/app_router.gr.dart';
