### ISSUE TITLE
No Overlay widget found error

### ISSUE THREAD

**Issue by DanielEidlin** [Milad-Akarie/auto_route_library#1351]
I'm using the latest version of `auto_route`  (currently 5.0.4) and a package called `showcaseview`. I get the following error from the `showcaseview` package when running my app:

```
I/flutter (31900): No Overlay widget found.
I/flutter (31900): Some widgets require an Overlay widget ancestor for correct operation.
I/flutter (31900): The most common way to add an Overlay to an application is to include a MaterialApp, CupertinoApp or Navigator widget in the runApp() call.
I/flutter (31900): The context from which that widget was searching for an overlay was:
I/flutter (31900):   ShowCaseWidget
I/flutter (31900): #0      Overlay.of.<anonymous closure> (package:flutter/src/widgets/overlay.dart:384:9)
I/flutter (31900): #1      Overlay.of (package:flutter/src/widgets/overlay.dart:387:6)
I/flutter (31900): #2      _OverlayBuilderState.addToOverlay (package:showcaseview/src/layout_overlays.dart:174:19)
I/flutter (31900): #3      _OverlayBuilderState.showOverlay (package:showcaseview/src/layout_overlays.dart:164:7)
I/flutter (31900): #4      _OverlayBuilderState.initState.<anonymous closure> (package:showcaseview/src/layout_overlays.dart:129:41)
I/flutter (31900): #5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
I/flutter (31900): #6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
I/flutter (31900): #7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
I/flutter (31900): #8      _invoke (dart:ui/hooks.dart:145:13)
I/flutter (31900): #9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
I/flutter (31900): #10     _drawFrame (dart:ui/hooks.dart:112:31)
```

Is there any solution for this?

**Comment by DanielEidlin** [comment]
It seems to be a problem with showcaseview.
