### ISSUE TITLE
v6.0.0-rc6 Nested navigation not working as expected

### ISSUE THREAD

**Issue by natintosh** [Milad-Akarie/auto_route_library#1403]
v6.0.0-rc-6 Keeps throwing the following error on `nested navigation` routing

```
E/flutter (23664): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 
E/flutter (23664): Looks like you're trying to navigate to a nested route without adding their parent to stack first
E/flutter (23664): try navigating to DashboardRoute -> AccountRoute -> SettingsRoute
E/flutter (23664): #0      RoutingController._matchOrReportFailure (package:auto_route/src/router/controller/routing_controller.dart:203:9)
E/flutter (23664): #1      StackRouter._push (package:auto_route/src/router/controller/routing_controller.dart:1027:17)
E/flutter (23664): #2      StackRouter.push (package:auto_route/src/router/controller/routing_controller.dart:974:35)
E/flutter (23664): #3      AccountScreen.build.<anonymous closure> (package:honeycomb/app/account/account_screen.dart:80:36)
E/flutter (23664): #4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1096:21)
E/flutter (23664): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
E/flutter (23664): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
E/flutter (23664): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
E/flutter (23664): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
E/flutter (23664): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
E/flutter (23664): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
E/flutter (23664): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
E/flutter (23664): #12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
E/flutter (23664): #13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
E/flutter (23664): #14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
E/flutter (23664): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
E/flutter (23664): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (23664): #17     _invoke1 (dart:ui/hooks.dart:164:13)
E/flutter (23664): #18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
E/flutter (23664): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
E/flutter (23664): 
```
Using auto tabs router

```dart
AutoTabsRouter(
      routes: const [
        HomeRoute(),
        TrackOrderRoute(),
        NotificationsRoute(),
        AccountRoute()
      ],
      builder: (context, child) {
        final tabsRouter = AutoTabsRouter.of(context);
        return Scaffold(
          body: child,
          bottomNavigationBar: NavigationBar(
            selectedIndex: tabsRouter.activeIndex,
            destinations: navigationItems,
            backgroundColor: context.theme.colorScheme.surface,
            onDestinationSelected: (index) {
              tabsRouter.setActiveIndex(index);
            },
          ),
        );
      },
    );
```

I am trying to `SettingsRouter` from `AccountRoute`

```dart
context.router.push(const SettingsRoute());
```

My current auto router config

```dart
@AutoRouterConfig()
class AppRouter extends $AppRouter {
  AppRouter([super.navigatorKey]);

  @override
  List<AutoRoute> get routes {
    return [
      AutoRoute(
        path: '/',
        page: SplashRoute.page,
      ),
      AutoRoute(
        path: '/dashboard',
        page: DashboardRoute.page,
        children: [
          RedirectRoute(path: '', redirectTo: 'home'),
          AutoRoute(
            path: 'home',
            page: HomeRoute.page,
          ),
          AutoRoute(
            path: 'track-order',
            page: TrackOrderRoute.page,
          ),
          AutoRoute(
            path: 'notifications',
            page: NotificationsRoute.page,
          ),
          AutoRoute(
            path: 'account',
            page: AccountRoute.page,
            children: [
              AutoRoute(
                path: 'settings',
                page: SettingsRoute.page,
              ),
            ],
          ),
        ],
      ),
      AutoRoute(
        path: '/onboarding',
        page: OnboardingRoute.page,
      ),
      AutoRoute(
        path: '/authentication',
        page: AuthenticationRoute.page,
      ),
    ];
  }
}
```

**Comment by natintosh** [comment]
I've searched for similar/previous issues none of them seems to work since EmtryRouterPage EmtryRouterWidget has been removed from v6.0.0

**Comment by Milad-Akarie** [comment]
@natintosh do you have an AutoRouter() widget inside of DashboardScreen?

**Comment by natintosh** [comment]
No, I don't have AutoRouter inside DashboardScreen

Here's how my DashboardScreen look like currently

```dart
@override
  Widget build(BuildContext context, WidgetRef ref) {
    return AutoTabsRouter(
      routes: const [
        HomeRoute(),
        TrackOrderRoute(),
        NotificationsRoute(),
        AccountRoute()
      ],
      builder: (context, child) {
        final tabsRouter = AutoTabsRouter.of(context);
        return Scaffold(
          body: child,
          bottomNavigationBar: NavigationBar(
            selectedIndex: tabsRouter.activeIndex,
            destinations: navigationItems,
            backgroundColor: context.theme.colorScheme.surface,
            onDestinationSelected: (index) {
              tabsRouter.setActiveIndex(index);
            },
          ),
        );
      },
    );
  }
```

**Comment by Milad-Akarie** [comment]
@natintosh I think I know what went wrong here.
you have your `SettingsRoute` as a child of `AccountRoute` but I don't think your account route has an AutoRouter() widget to render it's child routes [SettingRoute]
try this setup for account and settings route
```dart 

        AutoRoute(
            path: 'account',
            page: AccountSettingsRoute.page,
            children: [
           // this will render on /account because it has an empty path
             AutoRoute(
                path: '',
                page: AccountRoute.page,
              ),
              AutoRoute(
                path: 'settings',
                page: SettingsRoute.page,
              ),
            ],
          ),
```

 make your EmptyRouterScreen for account and settings route
```dart
@RoutePage()
class AccountSettingsScreen extends AutoRouter{};
```

**Comment by natintosh** [comment]
Oh, I think I get it now. So, for every ancestor, I need to extend `AutoRouter`. So this is pretty much how EmtryRouterPage or EmtryRouterWidget behaved in the previous version

**Comment by Milad-Akarie** [comment]
@natintosh exactly, every parent-route-page must have an `AutoRouter` or an `AutoTabsRouter` widgets to render it's children.
