### ISSUE TITLE
Set initial Route with v6.04

### ISSUE THREAD

**Issue by pbahr97** [Milad-Akarie/auto_route_library#1454]
Hi there,

im new to auto_route and struggling with finding out how to set a initial route depending on my shared_prefs.

i want to configure the initial route before building the marterial app something like that:
```dart
  Future _setupRouter() async {
    _appRouter = AppRouter();

/*      if (providerLoggedIn) {
        return initialRouteName = ...
      }*/
      if (onboardingDone) {
        return initialRoute = "Home";
      } else {
        return initialRoute = "Onboarding";
      }
  }
```

and later use it in the MaterialApp.router like this:

```dart
    return MaterialApp.router(
      title: "MyApp",
      debugShowCheckedModeBanner: false,
      routerConfig: router.config(),
      routeInformationParser: router.defaultRouteParser(),
      routerDelegate: router.delegate(initialRoutes: [initialRouteName]),
...
```

**Comment by Milad-Akarie** [comment]
@pbahr97  first of all you should know that router.config() has both routeInformParster and routerDelegate instances so no need to pass them separately, I don't think MaterialApp allows it anyways.
as for passing the initial route you can do that in two ways 
1- pass the route the `router.config(initialRoutes:[MyInitialRoute()])`

2- put a guard on your initial route and have it redirect to OnBoarding route when needed

**Comment by pbahr97** [comment]
Nevermind I think I understand what you mean.
I implemented it like this now:

```dart
// main.dart
  Future _setupRouter() async {
    _appRouter = AppRouter();

      if (onboardingDone) {
        _appRouter.setInitialRoutes([
          AdaptiveRoute(page: HomeRoute.page),
          AdaptiveRoute(page: OboardingRoute.page)
        ]);
      } else {
        _appRouter.setInitialRoutes([
          AdaptiveRoute(page: OboardingRoute.page),
          AdaptiveRoute(page: HomeRoute.page),
        ]);
      }
  }
```

and in my AppRouter

```dart
part 'router.gr.dart';

@AutoRouterConfig()
class AppRouter extends _$AppRouter {
  late List<AdaptiveRoute> initialRoutes;

  void setInitialRoutes(List<AdaptiveRoute> routes) {
    initialRoutes = routes;
  }

  @override
  RouteType get defaultRouteType => const RouteType.adaptive();

  @override
  late final List<AutoRoute> routes = [
    ...initialRoutes,
    AdaptiveRoute(page: HomeRoute.page),
  ];
}
```

**Comment by pbahr97** [comment]
But now I run into this issue:
`
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Can not resolve initial route
#0      AutoRouterDelegate.setInitialRoutePath (package:auto_route/src/router/controller/auto_router_delegate.dart:83:7)
#1      _RouterState._processParsedRouteInformation.<anonymous closure> (package:flutter/src/widgets/router.dart:716:34)
#2      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:39)
#3      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:708:8)
#4      _RouterState.restoreState (package:flutter/src/widgets/router.dart:584:7)
#5      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:917:5)
#6      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:903:7)
#7      _RouterState.didChangeDependencies (package:flutter/src/widgets/router.dart:655:11)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5119:11)
#9      ComponentElement.mount (package:flu<…>
`

**Comment by Milad-Akarie** [comment]
@pbahr97 somehting like this, althug I'd only pass the isOnboardingDone flag to the router and do the logic inside, also I don't see any initial paths in your code

**Comment by pbahr97** [comment]
I See...
Is the onDone a param of the PageRoute? Because I can't see it there

**Comment by pbahr97** [comment]
> @Pante yup I called it, you need to give your initial route a path of '/'. thinking about it, it does not make sense to give your OnBoardingPage an inital path, consider doing something like this
> 
> ```dart
>    AutoRoute(
>       page: HomeRoute.page,
>       path: '/',
>       guards: [
>         AutoRouteGuard.simple((resolver,_) {
>          if(onBoardingDone){
>            resolver.next(); // boarding is done continue navigation to HomePage
>          }else{
>          // pause navigation, do onBoarding, when onboard is done continue navigation to HomePage
>            push(OnBorderingRoute(onDone:() => resolver.next())); 
>          }
>       }),
>      ],
>     ),
> ```
> 
> this soluation is more practical because you might have initial-deep-links that won't work with approach you have in mind.
> 
> edit: use .simple instead of redirect

I See... 
i didnt quite understand the guards principle.
Is the onDone param something existing in the PageRoute? Because I can not see it there.

**Comment by pbahr97** [comment]
> > @Pante yup I called it, you need to give your initial route a path of '/'. thinking about it, it does not make sense to give your OnBoardingPage an inital path, consider doing something like this
> > ```dart
> >    AutoRoute(
> >       page: HomeRoute.page,
> >       path: '/',
> >       guards: [
> >         AutoRouteGuard.simple((resolver,_) {
> >          if(onBoardingDone){
> >            resolver.next(); // boarding is done continue navigation to HomePage
> >          }else{
> >          // pause navigation, do onBoarding, when onboard is done continue navigation to HomePage
> >            push(OnBorderingRoute(onDone:() => resolver.next())); 
> >          }
> >       }),
> >      ],
> >     ),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this soluation is more practical because you might have initial-deep-links that won't work with approach you have in mind.
> > edit: use .simple instead of redirect
> 
> I See... i didnt quite understand the guards principle. Is the onDone param something existing in the PageRoute? Because I can not see it there.

I See I can add it to the Route. Ok thanks for that!

**Comment by Milad-Akarie** [comment]
@pbahr97 close this if you have no more questions.

**Comment by pbahr97** [comment]
> @pbahr97 close this if you have no more questions.

I still get a small issue. Im sure this can be solved easy:

This is my AppRouter:

```dart
@AutoRouterConfig()
class AppRouter extends _$AppRouter {
  late bool onBoardingDone;

  late List<AdaptiveRoute> initialRoutes;

  AppRouter({required this.onBoardingDone});

  @override
  RouteType get defaultRouteType => const RouteType.adaptive();

  @override
  late final List<AutoRoute> routes = [
    AutoRoute(page: HomeRoute.page, path: "/", guards: [
      AutoRouteGuard.redirect((resolver) {
        if(onBoardingDone){
          resolver.next(); // boarding is done continue navigation to HomePage
          return null;
        }else{
          // pause navigation, do onBoarding, when onboard is done continue navigation to HomePage
          push(OnboardingRoute(onDone: () => resolver.next()));
          return null;
        }
      }),
    ]),
    AutoRoute(page: VouchersRoute.page),
    AutoRoute(page: FaqsRoute.page),
    AutoRoute(page: ContactRoute.page),
  ];
}
```

Error:
`
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:auto_route/src/router/controller/auto_route_guard.dart': Failed assertion: line 92 pos 12: '!isResolved': Make sure `resolver.next()` is only called once.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      NavigationResolver.next (package:auto_route/src/router/controller/auto_route_guard.dart:92:12)
#3      _AutoRouteGuardRedirectCallback.onNavigation (package:auto_route/src/router/controller/auto_route_guard.dart:49:14)
#4      StackRouter._canNavigate (package:auto_route/src/router/controller/routing_controller.dart:1249:13)
#5      StackRouter._pushAllGuarded (package:auto_route/src/router/controller/routing_controller.dart:1190:17)
#6      StackRouter._popUntilOrPushAll (package:auto_route/src/router/controller/routing_controller.dart:1013:12)
#7      StackRouter._navigateAll (package:auto_route/src/router/controller/rou<…>
`

**Comment by mirland** [comment]
Hi @Milad-Akarie , I had a question regarding initial routes in nested routes.
Suppose this case, you have one section (for example the onboarding) which contains some internal pages:

```dart
 AutoRoute(
        page: SectionRouter.page,
        path: '/something',
        children: [
          AutoRoute(
            path: 'subpath', // ** Not empty **
            page: Route.page,
            // initial: true, not allowed
          ),
          ...
        ],
)
```
In this case, if I want to use the `'subpath'` I have two options:
1. don't use the subpath and I change it for `''`. I don't like it because the library is limiting me to define `/something/subpath` as an initial route.
2. I define another guard checking that is the first page or something like that. It's not clear and clean for this case

So, what do you think? What's the best way to go in this case? Because at least for me it's a common case

Thanks for the hard work!

**Comment by Milad-Akarie** [comment]
@mirland  ya maybe taking away "initial" wasn't a good idea, anyways what initial did in previous versions was automatically add a redirect route which you can do manually as well 

```dart
 AutoRoute(
        page: SectionRouter.page,
        path: '/something',
        children: [
          Redirect(path: '', redirectTo: 'subpath')
          AutoRoute(
            path: 'subpath', // ** Not empty **
            page: Route.page,
            // initial: true, not allowed
          ),
          ...
        ],
)
```

**Comment by mirland** [comment]
Awesome, yes I didn't consider it, but `RedirectRoute` it's the way to go at least for now!

Thanks for the quick response!
