### ISSUE TITLE
AutoRoute Helper is not working in Android Studio

### ISSUE THREAD

**Issue by mag1c-dev** [Milad-Akarie/auto_route_library#1511]
Hi, thanks for your great library!

I have an issue with AutoRoute Helper plugin, it is not working in my Android Studio
Plugin version: 0.1.3
Android Studio Electric Eel | 2022.1.1 Patch 1 Build #AI-221.6008.13.2211.9514443, built on January 21, 2023

![2023-04-24 13 25 07](https://user-images.githubusercontent.com/48649647/233916142-1a869321-dd6e-4e3d-9d0b-4976e70170a7.gif)

**Comment by sh4msi** [comment]
I installed the plugin without problems and reset Android Studio
But nothing was added to the menus so I could work with it


```
Android Studio Electric Eel | 2022.1.1 Patch 2
Build #AI-221.6008.13.2211.9619390, built on February 17, 2023
Runtime version: 11.0.15+0-b2043.56-9505619 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry:
     external.system.auto.import.disabled=true
     ide.text.editor.with.preview.show.floating.toolbar=false
     ide.instant.shutdown=false

Non-Bundled Plugins:
     com.herbert.george.flutter-snippets (2.1.1-stable-1)
     com.bloc.intellij_generator_plugin (3.4.0)
     mobi.hsz.idea.gitignore (4.4.0)
     Dart (221.6103.1)
     com.ixigua.flutter_asset_iteral (1.7.7)
     com.autoroute.helper (0.1.3)
     pl.pszklarska.pubversionchecker (1.3.5)
     com.developerphil.adbidea (1.6.8)
     io.flutter (73.0.1)
     cn.yiiguxing.plugin.translate (3.4.2)
```

**Comment by sh4msi** [comment]
I updated it to **2022.2.1** and it gave the plugin an **error**

**Comment by dhruvanbhalara** [comment]
> I updated it to **2022.2.1** and it gave the plugin an **error**
> 
> Android Studio Flamingo | 2022.2.1 Build #AI-222.4459.24.2221.9862592, built on March 31, 2023

The plugin is not supported in the latest version of android studio yet.

**Comment by Milad-Akarie** [comment]
Hello,my vacation ends tomorrow, this will be the first thing I handle.

**Comment by dhruvanbhalara** [comment]
> Hello,my vacation ends tomorrow, this will be the first thing I handle.

Hope you had a good vacation.

**Comment by zhgwu** [comment]
> @sh4msi have you tried the new version yet?

I have tried version 0.1.4 in Android Studio Flamingo | 2022.2.1 but still not working.

**Comment by sh4msi** [comment]
> @sh4msi have you tried the new version yet?

The new version is not available for me

![image](https://user-images.githubusercontent.com/6229984/234884131-cd59358c-1e8c-4b5a-8bf0-c4809ed2969d.png)

**Comment by Milad-Akarie** [comment]
@sh4msi aren't using Flamingo?

**Comment by sh4msi** [comment]
New version not uploaded

![image](https://user-images.githubusercontent.com/6229984/234895692-dba541a9-dd13-4de1-b40f-faebb26abd15.png)

**Comment by Milad-Akarie** [comment]
@sh4msi that means it's not approved yet, you can download it manually if you want 
https://github.com/Milad-Akarie/auto_route_library/blob/master/tools/AutoRoute-Helper-0.1.4.jar

**Comment by perfect-deform** [comment]
**Not showing anything on windows 11 25357.1**
Android Studio Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 19, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    gradle.version.catalogs.dynamic.support=true

Non-Bundled Plugins:
    dev.polek.adbwifi (1.2.5)
    com.bloc.intellij_generator_plugin (3.4.0)
    Dart (222.4560)
    com.localizely.flutter-intl (1.18.1-2022.2)
    com.autoroute.helper (0.1.4)
    andrasferenczi.dart-data-plugin (0.2.0)
    com.clutcher.comments_highlighter (2023.3.2)
    io.flutter (73.0.2)
    de.mariushoefler.flutter_enhancement_suite (1.6.0)


**Getting IDE error on MacOS 13.3.1 (a) (22E772610a)**
Android Studio Flamingo | 2022.2.1
Build #AI-222.4459.24.2221.9862592, built on March 31, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 6
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    gradle.version.catalogs.dynamic.support=true

Non-Bundled Plugins:
    Dart (222.4582)
    com.autoroute.helper (0.1.4)
    io.flutter (73.0.2)
`
java.awt.IllegalComponentStateException: contentPane cannot be set to null.
 at java.desktop/javax.swing.JRootPane.setContentPane(Unknown Source)
 at java.desktop/javax.swing.JDialog.setContentPane(Unknown Source)
 at JFrameDialog.<init>(JFrameDialog.java:39)
 at JFrameDialog.show(JFrameDialog.java:102)
 at come.autoroute.helper.autoroutehelper.actions.CreateRoutePageAction.actionPerformed(CreateRoutePageAction.kt:37)
 at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
 at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:294)
 at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
 at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:294)
 at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$4(ActionMenuItem.java:293)
 at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:227)
 at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:286)
 at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:67)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
 at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$3(ActionMenuItem.java:109)
 at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
 at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
 at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
 at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:546)
 at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:578)
 at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
 at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.Component.processEvent(Unknown Source)
 at java.desktop/java.awt.Container.processEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
 at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
 at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
 at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
 at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
 at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
 at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
`
