### ISSUE TITLE
Build Runner Efficiency Warning

### ISSUE THREAD

**Issue by WoodyMKD** [Milad-Akarie/auto_route_library#1737]
Running `flutter pub run build_runner build` after upgrading a couple of libraries (including auto_route). Everything builds successful, but i do get these warnings:

```
[WARNING] build_resolvers:transitive_digests on lib/features/home/presentation/graphs/app_graph.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/configuration/presentation/screens/account/account_screen.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/home/presentation/screens/introduction.screen.route.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/home/presentation/screens/splash.screen.route.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/home/presentation/screens/home.screen.route.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/profile_management/presentation/screens/create_profile/create_new_profile_screen.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/configuration/presentation/screens/settings_screen.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/profile_management/presentation/screens/edit_profile_screen.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/home/presentation/widgets/tabs/home_tabs.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/home/presentation/widgets/home_header_view.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/core/presentation/widgets/input/eon_search_placeholder.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/configuration/presentation/widgets/popup_button.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/contact_management/presentation/widgets/dialogs/qr_code_generate_dialog/generate_qr_code_dialog.widget.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/contact_management/presentation/widgets/qr_scan.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/connecting/presentation/tabs/contact_requests_tab.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/contact_management/presentation/tabs/contacts_home_tab.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/contact_management/presentation/tabs/groups_home_tab.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/contact_management/presentation/screens/eon_search_new_screen.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/contact_management/presentation/graphs/add_contact_graph.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/contact_management/presentation/widgets/group_selection_view.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/contact_management/presentation/widgets/group_contacts_view.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/authentication/presentation/screens/login.screen.route.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/authentication/presentation/screens/forgot_password/forgot_password_input_screen.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/authentication/presentation/screens/setup_screen.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/authentication/presentation/screens/profile_selection_screen.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/authentication/presentation/screens/sign_up/sign_up_full_name_screen.route.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/authentication/presentation/screens/sign_up/sign_up_email_and_password_screen.route.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/authentication/presentation/screens/sign_up/sign_up_phone_screen.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/authentication/presentation/graphs/sign_up_graph.route.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/features/notifications/presentation/tabs/notification_tab.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on lib/core/presentation/utils/navigation/app_router.dart:
Unable to read asset, could not compute transitive deps: eon|lib/core/presentation/utils/navigation/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps

```

**Comment by yakupemeksiz** [comment]
I've the same issue. Any updates? @Milad-Akarie

**Comment by chiphan-makebetter** [comment]
Same here?

**Comment by AgonXhaferi** [comment]
I've also recently had this issue, any updates?

**Comment by Adam-Langley** [comment]
+1

**Comment by PawlikMichal25** [comment]
It's also happening in our project, however the generation fails. 
The log is super long and ends with:
```
#1      LibraryContext.remove (package:analyzer/src/dart/analysis/library_context.dart:265:20)
#2      AnalysisDriver._removePotentiallyAffectedLibraries (package:analyzer/src/dart/analysis/driver.dart:1777:22)
#3      AnalysisDriver._applyPendingFileChanges (package:analyzer/src/dart/analysis/driver.dart:1243:7)
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2152:18)
<asynchronous suspension>
]
```

**Comment by PawlikMichal25** [comment]
Seems like a duplicate of https://github.com/Milad-Akarie/auto_route_library/issues/1729

**Comment by JoshuaSardinha** [comment]
+1

**Comment by Rejomeee** [comment]
+1

**Comment by Rejomeee** [comment]
For my case. I used CustomRoute instead of the AutoRoute. The warning is gone after adding on transitionsBuilder property.

**Comment by Rejomeee** [comment]
+1

**Comment by Afur** [comment]
+1

**Comment by Milad-Akarie** [comment]
@Afur confirm the fix in the latest auto_route_generator?

**Comment by Afur** [comment]
@Milad-Akarie works, thanks 👌
