### ISSUE TITLE
Inherited params not working and wrong navigation

### ISSUE THREAD

**Issue by tomasweigenast** [Milad-Akarie/auto_route_library#1827]
I have the following route hierarchy:
```dart
AdaptiveRoute(page: OrdersRouteWrapper.page, path: 'orders', children: [
            AdaptiveRoute(page: OrdersRoute.page, path: '', initial: true),
            AdaptiveRoute(
                page: OrderRoute.page,
                path: ':orderId',
                children: [AdaptiveRoute(page: OrderPaymentProofRoute.page, path: "payment-proof")]),
          ])
```

(it is not the root, there are other routes above /orders, and I skip them for simplicity).

First of all, I want to mention that I want to navigate to `OrderPaymentProofRoute` from `OrdersRoute`, but it will send me to `OrderRoute` instead of `OrderPaymentProofRoute`.

But I navigate first to `OrderRoute`, and then `context.navigateTo(OrderPaymentProofRoute());` it throws the following exception:
```
Error [Failed to parse [String] orderId value from null]
I/flutter (12453): #0      Parameters.getString (package:auto_route/src/common/parameters.dart:61:7)
I/flutter (12453): #1      new _$AppRouter.<anonymous closure>.<anonymous closure> (package:cercanni_customers/ui/router.gr.dart:140:50)
I/flutter (12453): #2      RouteData.argsAs (package:auto_route/src/route/route_data.dart:101:22)
I/flutter (12453): #3      new _$AppRouter.<anonymous closure> (package:cercanni_customers/ui/router.gr.dart:138:30)
I/flutter (12453): #4      RootStackRouter._pageBuilder (package:auto_route/src/router/controller/root_stack_router.dart:169:20)
I/flutter (12453): #5      StackRouter._addEntry (package:auto_route/src/router/controller/routing_controller.dart:1547:29)
I/flutter (12453): #6      StackRouter._pushAllGuarded (package:auto_route/src/router/controller/routing_controller.dart:1522:29)
I/flutter (12453): <asynchronous suspension>
I/flutter (12453): 
```

OrderPaymentProofView:
```dart
@RoutePage()
class OrderPaymentProofView extends StatelessWidget {
  final String orderId;

  const OrderPaymentProofView({@PathParam.inherit() required this.orderId, super.key});
}
```

OrderView:
```dart
@RoutePage()
class OrderView extends HookWidget {
  final String orderId;

  const OrderView({@pathParam required this.orderId, super.key});
}
```

Obviously when I navigate to OrderRoute I pass the orderId parameter.

Versions:
```yaml
auto_route: ^7.8.0
auto_route_generator: ^7.3.1
```

**Comment by tomasweigenast** [comment]
Is this project abandoned?

**Comment by jakelaws1** [comment]
@tomasweigenast did you ever get a work around? Just pass the parameters manually instead of inheriting? Frustrating this was never addressed

**Comment by tomasweigenast** [comment]
I just pass the params manually
