### ISSUE TITLE
Failed to navigate to previous page on clicking back button of both device or appbar.

### ISSUE THREAD

**Issue by maxchu92** [Milad-Akarie/auto_route_library#1885]
# Failed to navigate to previous page on clicking back button of both device or appbar.

Please refer to my repository:
[Repository Link](https://github.com/maxchu92/flutter_autoroute_test_app/tree/main)

This project demostrate how the app is unable to return to previous page with back button on both device and appbar. I suspect it has to do with the latest version of Flutter.

Upon navigating back, an error shows up:

```
D/EGL_emulation( 4411): app_time_stats: avg=179.78ms min=5.24ms max=5264.16ms count=33
E/flutter ( 4411): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: Class 'TabsRouter' has no instance getter 'identifier'.
E/flutter ( 4411): Receiver: Instance of 'TabsRouter'
E/flutter ( 4411): Tried calling: identifier
E/flutter ( 4411): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter ( 4411): #1      RoutingController._removeTopRouterOf (package:auto_route/src/router/controller/routing_controller.dart:90:15)
E/flutter ( 4411): #2      StackRouter._removeRoute (package:auto_route/src/router/controller/routing_controller.dart:1152:5)
E/flutter ( 4411): #3      StackRouter.removeRoute (package:auto_route/src/router/controller/routing_controller.dart:1136:5)
E/flutter ( 4411): #4      AutoRouteNavigatorState.build.<anonymous closure> (package:auto_route/src/router/widgets/auto_route_navigator.dart:103:31)
E/flutter ( 4411): #5      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5284:28)
E/flutter ( 4411): #6      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5243:9)
E/flutter ( 4411): <asynchronous suspension>
E/flutter ( 4411):
D/EGL_emulation( 4411): app_time_stats: avg=3462.79ms min=12.31ms max=130951.63ms count=38
Lost connection to device.

Exited.

```

### Tested Environment
- Tested on fresly installed environment
- VS Code `1.87.1`
- Flutter `v3.19.3`
- auto_route `v7.8.4` / `v7.8.5`

### Steps to reproduce error
1. Click on `Home` button.
2. Click on either device or appbar `Back` button.

### Result of Flutter version
flutter --version
```
Flutter 3.19.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ba39319843 (5 days ago) • 2024-03-07 15:22:21 -0600
Engine • revision 2e4ba9c6fb
Tools • Dart 3.3.1 • DevTools 2.31.1
```

**Comment by maxchu92** [comment]
Sorry, my mistake, just noticed a reply from another post to solve this issue. Thank you.
