### ISSUE TITLE
popForced and popUntilRoot is broken after 7.8.4

### ISSUE THREAD

**Issue by YDA93** [Milad-Akarie/auto_route_library#1897]
After I upgraded from 7.8.4 I noticed i started to get the following error after I run either **popForced** or **popUntilRoot**:
`_AssertionError ('package:flutter/src/widgets/navigator.dart': Failed assertion: line 5277 pos 12: '!_debugLocked': is not true.)`

Everything is working perfectly when I downgrade to 7.8.4

<details>
<summary> Stack Trace</summary>

```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: The following exception was thrown Caught by runZonedGuarded:
flutter: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5277 pos 12: '!_debugLocked': is not true.
flutter:
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5277:12)
#3      NavigatorState.popUntil (package:flutter/src/widgets/navigator.dart:5324:7)
#4      StackRouter.popUntilRoot (package:auto_route/src/router/controller/routing_controller.dart:1325:33)
#5      ScreenPaymentResultOrder.build.<anonymous closure> (package:fecare/apps/store/screens/screen_payment_result_order.dart:46:24)
#6      ModalRoute.onPopInvoked (package:flutter/src/widgets/routes.dart:1578:30)
#7      AutoRouteNavigatorState.build.<anonymous closure> (package:auto_route/src/router/widgets/auto_route_navigator.dart:106:21)
#8      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5284:28)
#9      NavigatorState.popUntil (package:flutter/src/widgets/navigator.dart:5324:7)
#10     StackRouter.popUntilRoot (package:auto_route/src/router/controller/routing_controller.dart:1325:33)
#11     ScreenPaymentResultOrder.build.<anonymous closure> (package:fecare/apps/store/screens/screen_payment_result_order.dart:46:24)
#12     ModalRoute.onPopInvoked (package:flutter/src/widgets/routes.dart:1578:30)
#13     NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5246:25)
<asynchronous suspension>
#14     StackRouter.maybePop (package:auto_route/src/router/controller/routing_controller.dart:1091:9)
<asynchronous suspension>
flutter: ----------------------------------------------------

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building AutoRouteNavigator(dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#9ce9a]], state: AutoRouteNavigatorState#d505c):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5277 pos 12: '!_debugLocked': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    EmptyTabScreenHome EmptyTabScreenHome:file:///Users/yousefalmutairi/Desktop/dev/fecare_flutter/lib/routes/router.gr.dart:226:22

When the exception was thrown, this was the stack:
#2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5277:12)
#3      NavigatorState.popUntil (package:flutter/src/widgets/navigator.dart:5324:7)
#4      StackRouter.popUntilRoot (package:auto_route/src/router/controller/routing_controller.dart:1325:33)
#5      ScreenPaymentResultOrder.build.<anonymous closure> (package:fecare/apps/store/screens/screen_payment_result_order.dart:46:24)
#6      ModalRoute.onPopInvoked (package:flutter/src/widgets/routes.dart:1578:30)
#7      _RouteEntry.pop (package:flutter/src/widgets/navigator.dart:3116:11)
#8      _RouteEntry.markForPop (package:flutter/src/widgets/navigator.dart:3322:5)
#9      DefaultTransitionDelegate.resolve.handleExitingRoute (package:flutter/src/widgets/navigator.dart:1105:28)
#10     DefaultTransitionDelegate.resolve (package:flutter/src/widgets/navigator.dart:1144:7)
#11     TransitionDelegate._transition (package:flutter/src/widgets/navigator.dart:921:53)
#12     NavigatorState._updatePages (package:flutter/src/widgets/navigator.dart:4181:43)
#13     NavigatorState.didUpdateWidget (package:flutter/src/widgets/navigator.dart:3841:7)
#14     StatefulElement.update (package:flutter/src/widgets/framework.dart:5652:55)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#27     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#32     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#33     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#34     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#35     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#36     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#37     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#41     _invoke (dart:ui/hooks.dart:314:10)
#42     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#43     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════
```

</details>

</summary>

**Comment by Milad-Akarie** [comment]
How to repreduce?

**Comment by YDA93** [comment]
@Milad-Akarie 
1. Upgrade to 7.9.2
2. Use AutoTabsScaffold
3. Push to screen that has PopScope with canPop set to false
4. Run `context.router.popForced();`

**Comment by Milad-Akarie** [comment]
@YDA93 I think there might be an issue with your implementation of the OnPopInnvoked, the only reason it worked before auto-route wasn't handling it right.
This is how onPopInvoked should be implemented now, otherwise `popForced` will trigger the `onPopInvoked` 

```dart
       onPopInvoked: (didPop) {
              if(didPop){
                // we already popped do nothing
                return;
              }
              // else force pop, or show a dialog that finally calls popForced
              context.router.popForced();
            },
```
if my assumption is not correct please provide your implementation for further investigation.

**Comment by YDA93** [comment]
@Milad-Akarie 

I apologize for my ignorance and thanks for your help.

**Comment by Milad-Akarie** [comment]
@YDA93 don't be harsh on your self, auto_route should've supported PopScope sooner
