### ISSUE TITLE
AutoTabsRouterTabBarState was disposed with active Ticker

### ISSUE THREAD

**Issue by p-guetschow** [Milad-Akarie/auto_route_library#1910]
I am using the Tabbar from the AutoTabsRouter. In my integration tests the following exception is thrown:

```The following assertion was thrown while finalizing the widget tree:
_AutoTabsRouterTabBarState#8fe06(tickers: tracking 1 ticker) was disposed with an active Ticker.
_AutoTabsRouterTabBarState created a Ticker via its TickerProviderStateMixin, but at the time
dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before
calling super.dispose().
Tickers used by AnimationControllers should be disposed by calling dispose() on the
AnimationController itself. Otherwise, the ticker will leak.
The offending ticker was:
  _WidgetTicker(created by _AutoTabsRouterTabBarState#8fe06)
  The stack trace when the _WidgetTicker was actually created was:
  #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:71:40)
  #1      new Ticker (package:flutter/src/scheduler/ticker.dart:73:6)
  #2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart)
  #3      TickerProviderStateMixin.createTicker
  (package:flutter/src/widgets/ticker_provider.dart:298:34)
  #4      new AnimationController.unbounded
  (package:flutter/src/animation/animation_controller.dart:278:21)
  #5      new TabController (package:flutter/src/material/tab_controller.dart:114:51)
  #6      _AutoTabsRouterTabBarState._updateTabController
  (package:auto_route/src/router/widgets/auto_tabs_router.dart:650:22)
  #7      _AutoTabsRouterTabBarState._setupController
  (package:auto_route/src/router/widgets/auto_tabs_router.dart:629:5)
  #8      AutoTabsRouterState.didChangeDependencies
  (package:auto_route/src/router/widgets/auto_tabs_router.dart:200:7)
```

When i apply the code from pull request https://github.com/Milad-Akarie/auto_route_library/pull/1909 the execption does not occur anymore

**Comment by Milad-Akarie** [comment]
@p-guetschow should be fixed in latest version

**Comment by p-guetschow** [comment]
Thanks
