### ISSUE TITLE
Flutter stable 1.20 breaking changes

### ISSUE THREAD

**Issue by sharpsan** [Milad-Akarie/auto_route_library#200]
This notice is pertinent to this library: https://groups.google.com/forum/#!searchin/flutter-announce/55998%7Csort:date/flutter-announce/yoq2VGi94q8/8pTsRL28AQAJ

I just upgraded to the newly-released stable Flutter release 1.20.  Looks like this is the exception I am experiencing when attempting to push routes.  For now, I am unable to push routes.

Console output:
```
E/flutter (29800): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 715 pos 12: 'navigator != null': is not true.
E/flutter (29800): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:46:39)
E/flutter (29800): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5)
E/flutter (29800): #2      HeroController.didPush 
package:flutter/…/widgets/heroes.dart:715
E/flutter (29800): #3      _NavigatorPushObservation.notify 
package:flutter/…/widgets/navigator.dart:2661
E/flutter (29800): #4      List.forEach  (dart:core-patch/growable_array.dart:302:8)
E/flutter (29800): #5      NavigatorState._flushObserverNotifications 
package:flutter/…/widgets/navigator.dart:3273
E/flutter (29800): #6      NavigatorState._flushHistoryUpdates 
package:flutter/…/widgets/navigator.dart:3240
E/flutter (29800): #7      NavigatorState.push 
package:flutter/…/widgets/navigator.dart:3507
E/flutter (29800): #8      NavigatorState.pushNamed 
package:flutter/…/widgets/navigator.dart:3400
E/flutter (29800): #9      ExtendedNavigatorState.push 
package:auto_route/src/extended_navigator.dart:315
E/flutter (29800): <asynchronous suspension>
E/flutter (29800): #10     RouterExtendedNavigatorStateX.pushDashboardRoute 
package:myproject_flutter/router/router.gr.dart:273
E/flutter (29800): #11     HomeDebuggingRoute.build.<anonymous closure> 
package:myproject_flutter/…/common/home_debugging_route.dart:41
E/flutter (29800): #12     _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:992
E/flutter (29800): #13     _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:1098
E/flutter (29800): #14     GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:184
E/flutter (29800): #15     TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:524
E/flutter (29800): #16     BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:284
E/flutter (29800): #17     BaseTapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:219
E/flutter (29800): #18     PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:477
E/flutter (29800): #19     PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:78
E/flutter (29800): #20     PointerRouter._dispatchEventToRoutes.<anonymous closure> 
package:flutter/…/gestures/pointer_router.dart:124
E/flutter (29800): #21     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (29800): #22     PointerRouter._dispatchEventToRoutes 
package:flutter/…/gestures/pointer_router.dart:122
E/flutter (29800): #23     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:108
E/flutter (29800): #24     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:220
E/flutter (29800): #25     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:200
E/flutter (29800): #26     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:158
E/flutter (29800): #27     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:104
E/flutter (29800): #28     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:88
E/flutter (29800): #29     _rootRunUnary  (dart:async/zone.dart:1206:13)
E/flutter (29800): #30     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (29800): #31     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)
E/flutter (29800): #32     _invoke1  (dart:ui/hooks.dart:267:10)
E/flutter (29800): #33     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5)
E/flutter (29800):
E/flutter (29800): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2422 pos 18: '!navigator._debugLocked': is not true.
E/flutter (29800): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:46:39)
E/flutter (29800): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5)
E/flutter (29800): #2      _RouteEntry.handlePush.<anonymous closure> 
package:flutter/…/widgets/navigator.dart:2422
E/flutter (29800): #3      TickerFuture.whenCompleteOrCancel.thunk 
package:flutter/…/scheduler/ticker.dart:401
E/flutter (29800): #4      _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (29800): #5      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (29800): #6      _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)
E/flutter (29800): #7      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)
E/flutter (29800): #8      Future._propagateToListeners  (dart:async/future_impl.dart:725:32)
E/flutter (29800): #9      Future._completeWithValue  (dart:async/future_impl.dart:529:5)
E/flutter (29800): #10     Future._asyncCompleteWithValue.<anonymous closure>  (dart:async/future_impl.dart:567:7)
E/flutter (29800): #11     _rootRun  (dart:async/zone.dart:1190:13)
E/flutter (29800): #12     _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (29800): #13     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)
E/flutter (29800): #14     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)
E/flutter (29800): #15     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
E/flutter (29800): #16     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
```

**Comment by NarHakobyan** [comment]
yeah, it's fully broken

**Comment by Milad-Akarie** [comment]
I'm on it

**Comment by NarHakobyan** [comment]
temporary soluton is to add `home` property.

```dart
        builder: ExtendedNavigator<Router>(
          key: _exNavigatorKey,
          router: Router(),
        ),
        home: SizedBox(),
```

**Comment by Milad-Akarie** [comment]
@NarHakobyan The generator won't run in the first place

**Comment by NarHakobyan** [comment]
it's working in my side

**Comment by Milad-Akarie** [comment]
@NarHakobyan What's your build_runner version?

**Comment by Milad-Akarie** [comment]
@sharpsan I bumped up some dependencies versions and the generation worked just fine, I couldn't reproduce the error you encountered, the example app worked just fine.  
try to update to auto_route_generator: 0.6.8 
flutter clean
pub cache repair
or manually deleting your pubspec.lock file

**Comment by NarHakobyan** [comment]
> @NarHakobyan What's your build_runner version?

build_runner: 1.9.0

**Comment by NarHakobyan** [comment]
@Milad-Akarie build_runner: ^1.10.0 requires SDK version >=2.10.0-0.0 <3.0.0, so autoroute will not work on stable channel

**Comment by sharpsan** [comment]
> @sharpsan I bumped up some dependencies versions and the generation worked just fine, I couldn't reproduce the error you encountered, the example app worked just fine.
> try to update to auto_route_generator: 0.6.8
> flutter clean
> pub cache repair
> or manually deleting your pubspec.lock file

Note: I am using `build_runner ^1.10.1`
After trying the suggestions you mentioned this is the console output I am getting back:
`flutter packages pub run build_runner build --delete-conflicting-outputs`
```
Precompiling executable...
Failed to precompile build_runner:build_runner:
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.9/lib/src/resolver.dart:340:10: Error: Method not found: 'SummaryBuilder'.
  return SummaryBuilder(sdkSources, sdk.context).build(
         ^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.9/lib/src/resolver.dart:329:7: Error: The setter 'useSummary' isn't defined for the class 'FolderBasedDartSdk'.
 - 'FolderBasedDartSdk' is from 'package:analyzer/src/dart/sdk/sdk.dart' ('../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.14/lib/src/dart/sdk/sdk.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'useSummary'.
    ..useSummary = false
      ^^^^^^^^^^
pub finished with exit code 1
```

**Comment by sharpsan** [comment]
My apologies, I failed to try deleting `pubspec.lock` before making my previous comment.  I deleted the file, fetched packages, re-ran the build runner command and the generation was successful.

However, the initial issue still persists: unable to push to any routes without an error being thrown (refer to original post for log)

**Comment by sharpsan** [comment]
What can I do/provide for us to get to the bottom of this issue?

**Comment by sharpsan** [comment]
> @Milad-Akarie build_runner: ^1.10.0 requires SDK version >=2.10.0-0.0 <3.0.0, so autoroute will not work on stable channel

Please note that these are the SDK constraints for `build_runner ^1.10.2` and not `^1.10.0/^1.10.1`

**Comment by DazzaH0** [comment]
I found the following here https://github.com/hivedb/hive/issues/387

Gets the generator working for me

pubspec.yaml

dev_dependencies:
  auto_route_generator: ^0.4.4
  build_runner: 1.10.0
  ..

dependency_overrides:
  analyzer: 0.39.14

**Comment by sharpsan** [comment]
I'm really not having issues with the generation aspect, but rather with pushing routes.

**Comment by sharpsan** [comment]
Turns out the breaking change wasn't directly related to auto_route.  Previously, I was awaiting a Future before returning a `MaterialApp` that included the routing information.  During `ConnectionState.waiting` a different empty `MaterialApp` would be returned.  
Unsure why this worked prior to Flutter 1.20.  Closing this issue.

**Comment by Holofox** [comment]
I could not solve the problem, routes still do not switch, throws exceptions:
```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 715 pos 12: 'navigator != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      HeroController.didPush (package:flutter/src/widgets/heroes.dart:715:12)
#3      _NavigatorPushObservation.notify (package:flutter/src/widgets/navigator.dart:2661:14)
#4      List.forEach (dart:core-patch/growable_array.dart:302:8)
#5      NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:3273:27)
#6      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3240:5)
#7      NavigatorState.pushAndRemoveUntil (package:flutter/src/widgets/navigator.dart:3630:5)
#8      NavigatorState.pushNamedAndRemoveUntil (package:flutter/src/widgets/navigator.dart:3480:12)
#9      ExtendedNavigatorState.pushAndRemoveUntil (package:aut<…>
```

```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2422 pos 18: '!navigator._debugLocked': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      _RouteEntry.handlePush.<anonymous closure> (package:flutter/src/widgets/navigator.dart:2422:18)
#3      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:401:15)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     Future._asyncCompleteWithValue.<anonymous closure><…>
Application finished.
```

**Comment by sharpsan** [comment]
Can you show what you had in main.dart before the hacky fix?

**Comment by Holofox** [comment]
@sharpsan,

```dart
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: _navigatorBuilder,
    );
  }
```

**Comment by sharpsan** [comment]
Sorry, couldn't reproduce the issue using the provided code.

**Comment by varundroid** [comment]
I am getting the following issues 

`Failed to precompile build_runner:build_runner:
../../flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.9/lib/src/resolver.dart:340:10: Error: Method not found: 'SummaryBuilder'.
  return SummaryBuilder(sdkSources, sdk.context).build(
         ^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.9/lib/src/resolver.dart:329:7: Error: The setter 'useSummary' isn't defined for the class 'FolderBasedDartSdk'.
 - 'FolderBasedDartSdk' is from 'package:analyzer/src/dart/sdk/sdk.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.14/lib/src/dart/sdk/sdk.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'useSummary'.
    ..useSummary = false
      ^^^^^^^^^^`

Not sure what I am missing.
