### ISSUE TITLE
On dialog pop + page pop after ('!_debugLocked': is not true.)

### ISSUE THREAD

**Issue by HeropolisDa2ny** [Milad-Akarie/auto_route_library#2017]
I've migrated my code from flutter navigator to a auto route navigator and I'm facing an issue on dialog pop.

I open a dialog and wait its response to decide if I should pop or not my current page.
The response of my dialog is true then I decide to pop my page.
Then because there is a double chained pop I'm receiving an error (that I wasn't receiving on flutter Navigator)

```
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4817 pos 12: '!_debugLocked': is not true.
      #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
      #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
      #2      NavigatorState._pushEntry (package:flutter/src/widgets/navigator.dart:4817:12)
      #3      NavigatorState.push (package:flutter/src/widgets/navigator.dart:4774:5)
      #4      showDialog (package:flutter/src/material/dialog.dart:1436:65)
```

```
final bool? result = await showDialog(
  context: context,
  builder: (context) => Dialog(
    child: ElevatedButton(
      onPressed: () => context.router.maybePop(true),
      child: Text('test'),
    ),
  ),
);

if (result == true) {
  context.router.maybePop(true);
}
```

I tried other way to see if it could solve the problem but it didn't work like :

```
if (result == true) {
  WidgetsBinding.instance.addPostFrameCallback((_) async {
    context.router.maybePop();
  });
}
```
or
```
if (result == true) {
  Future.delayed(
    Duration(seconds: 10),
    () {
      context.router.maybePop();
    },
  );
}
```

**Comment by HeropolisDa2ny** [comment]
This bug is pretty much annoying when your app doesn't wait for an api response.
You call an api method after a dialog confirmation and pop the page because the page isn't needed anymore and the error appears...

**Comment by PackRuble** [comment]
Same problem.

It helped me to wrap the page where the dialog is called in `WillPopScope` and use `onWillPop`. And `PopScope` gives an error like yours.

```
Flutter 3.22.3 • channel stable
auto_route: ^9.2.0
```

**Comment by HeropolisDa2ny** [comment]
> Same problem.
> 
> It helped me to wrap the page where the dialog is called in `WillPopScope` and use `onWillPop`. And `PopScope` gives an error like yours.
> 
> ```
> Flutter 3.22.3 • channel stable
> auto_route: ^9.2.0
> ```

I migrated to the `PopScope` and indeed it's producing the error but since I'm backing up to `WillPopScope` the pages doesn't want to close anymore. Idk what's happening..

**Comment by tpkowastaken** [comment]
My solution was to rethink the logic of the exit confirmation dialog and instead of returning back to the original function I just call removeLast() which removes the last page from the stack instead.

Original:
my_form.dart:
```dart
  void onTryingToExit() async {
    if (!_isFormDirty()) {
      context.router.popForced();
      return;
    }
    final shouldPop = await showExitConfirmationDialog(context);
    if (shouldPop == true && mounted) {
      context.router.popForced();
    }
  }
  
  return PopScope(
      canPop: false,
      onPopInvokedWithResult: (didPop, __) => onTryingToExit(context),
```

show_exit_confirmation_dialog.dart:
```dart
Future<bool?> showExitConfirmationDialog(BuildContext context) {
  return showDialog<bool>(
    context: context,
    builder: (context) => AlertDialog(
      title: const Text('Discard changes?'),
      content: const Text('Exit the page and discard changes?'),
      actions: [
        TextButton(
          onPressed: () => context.router.maybePop(false),
          child: const Text('Cancel'),
        ),
        TextButton(
          onPressed: () => context.router.maybePop(true),
          child: const Text(
            'Discard changes',
            style: TextStyle(color: Colors.red),
          ),
        ),
      ],
    ),
  );
}

```

After:

my_form.dart:
```dart
  void onTryingToExit(BuildContext context) async {
    if (!_isFormDirty()) {
      context.router.popForced();
      return;
    }
    showExitConfirmationDialog(context);
  }
  
  return PopScope(
      canPop: false,
      onPopInvokedWithResult: (didPop, __) => onTryingToExit(context),
```

show_exit_confirmation_dialog.dart:
```dart
Future<bool?> showExitConfirmationDialog(BuildContext context) {
  return showDialog<bool>(
    context: context,
    builder: (context) => AlertDialog(
      title: const Text('Discard changes?'),
      content: const Text('Exit and discard changes?'),
      actions: [
        TextButton(
          onPressed: () => context.router.maybePop(),
          child: const Text('cancel'),
        ),
        TextButton(
          onPressed: () => context.router.removeLast(),
          child: const Text(
            'Discard changes',
            style: TextStyle(color: Colors.red),
          ),
        ),
      ],
    ),
  );
}
```

**Comment by golfling** [comment]
Hey. In you example `onTryingToExit()` is triggered on every `pop()`. According to [doc](https://api.flutter.dev/flutter/widgets/PopScope-class.html) you need to skip this if `didPop == true`. 

It works for me: 


```dart
    return PopScope(
      canPop: false,
      onPopInvokedWithResult: (didPop, result) {
        if (didPop) return;

        confirmPop<bool>(
          context: context,
          onConfirm: context.router.popForced(result),
        );
      },
``` 

```dart
static Future<T?> confirmPop<T>({
    required BuildContext context,
    required void Function() onConfirm,
  }) =>
      showConfirmationDialog<T>(
        context: context,
        title: 'Title',
        onConfirm: () {
          Navigator.of(context, rootNavigator: true).pop();
          onConfirm();
        },
      );
```

**Comment by tpkowastaken** [comment]
```dart
canPop: false,
  onPopInvokedWithResult: (didPop, result) => onTryingToExit(didPop, result),
```
```dart
  void onTryingToExit(didPop, value) async {
    if (didPop) return;
    if (value != null || !_isFormDirty()) {
      context.router.popForced(value);
      return;
    }
    final shouldPop = await showExitConfirmationDialog(context);
    if (shouldPop == true && mounted && context.mounted) {
      SystemNavigator.pop();
    }
  }
```

After a lot of trial and error I've ended up with the code above. It does not throw any errors and is as stable as I could get it to be.
