### ISSUE TITLE
"Can not resolve initial route" on some users Android devices

### ISSUE THREAD

**Issue by escamoteur** [Milad-Akarie/auto_route_library#2119]
auto_route: 9.0.0

With our recent release that also included the switch to Flutter `3.27.1`  Suddenly we see in Sentry on certain Android devices this Exceptions:

```
FlutterError: Can not resolve initial route
  #0      AutoRouterDelegate.setInitialRoutePath (package:auto_route/src/router/controller/auto_router_delegate.dart:117)
  #1      _RouterState._processParsedRouteInformation.<fn> (package:flutter/src/widgets/router.dart:763)
  #2      _rootRunUnary (dart:async/zone.dart:1422)
  #3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:902)
  #4      Future._propagateToListeners (dart:async/future_impl.dart:931)
  #5      Future._completeWithValue (dart:async/future_impl.dart:707)
  #6      Future._chainForeignFuture.<fn> (dart:async/future_impl.dart:591)
  #7      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:43)
  #8      Future._chainForeignFuture (dart:async/future_impl.dart:587)
  #9      Future._chainFuture (dart:async/future_impl.dart:793)
  #10      Future._asyncCompleteUnchecked (dart:async/future_impl.dart:755)
```

at startup. Unfortunately where the Exception is created no additional information is included inside the Exception so we have no idea what is going on. It only happens on Android and not for all users.

**Comment by jaypokar** [comment]
Same issue with my android device.

**Comment by Milad-Akarie** [comment]
@escamoteur @jaypokar  This error means either the default window path which is normally "/" is changed in these devices or your route list doesn't handle the "/" path.

to be save you can always redirect unmatched routes to your home route using a wild-card.
e.g 
add `RedirectRoute(path: "*", redirectTo: "/")` at the end of your route list

**Comment by escamoteur** [comment]
How is that possible that there is a different default route than '/' on Android?
Am 8. Jan. 2025, 20:29 +0100 schrieb Milad Akarie ***@***.***>:

**Comment by Milad-Akarie** [comment]
@escamoteur I'm saying it's a possibility, the deep-link handler might've received an empty path or an unmatchable path, that's why I recommend having a safety wild-card net when working with deep-links.

maybe one of you can log the uri inside `DeepLinkTransformer`  callback  on these devices so we know what's going on.

**Comment by jaypokar** [comment]
> @escamoteur @jaypokar This error means either the default window path which is normally "/" is changed in these devices or your route list doesn't handle the "/" path.
> 
> to be save you can always redirect unmatched routes to your home route using a wild-card. e.g add `RedirectRoute(path: "*", redirectTo: "/")` at the end of your route list

this works perfectly actually we are opening app via other apps with geo location , after updating to flutter version 3.27.1. But , above solution works perfectly.

**Comment by escamoteur** [comment]
Same here. that this only started with the latest Flutter version. Unfortunately the place where the exception is thrown does not include the path that was passed in inside the exceptions message.

**Comment by 1mavic** [comment]
Hi, do you use some plugin for working with deep link?
If so, there were some breaking changes in 3.27
https://docs.flutter.dev/release/breaking-changes/deep-links-flag-change
May be this can cause exceptions.
