### ISSUE TITLE
How to use Firebase Analytics observer with Router? Exception occurs when trying to use it the regular way

### ISSUE THREAD

**Issue by sceee** [Milad-Akarie/auto_route_library#236]
Hi,

I am trying to use the Firebase Analytics `` with my AutoRoute Router. Unfortunately, the following exception happens when trying to use register the `FirebaseAnalyticsObserver` as `observer` either for the `MaterialApp` itself or for the `ExtendedNavigator<Router>` builder.

I tried the following ways but always the exception happens:
```
static FirebaseAnalytics analytics = FirebaseAnalytics();
static FirebaseAnalyticsObserver observer = FirebaseAnalyticsObserver(analytics: analytics);

return MaterialApp(
            debugShowCheckedModeBanner: false,
            builder: ExtendedNavigator<Router>(
              router: Router(),
              observers: [observer],
            ),
          );
```
or
```
static FirebaseAnalytics analytics = FirebaseAnalytics();
static FirebaseAnalyticsObserver observer = FirebaseAnalyticsObserver(analytics: analytics);

return MaterialApp(
            debugShowCheckedModeBanner: false,
            navigatorObservers: [observer],
            builder: ExtendedNavigator<Router>(
              router: Router(),
            ),
          );
```

Router is the generated router and routing works as expected without the observer.

<details>
  <summary>Exception</summary>
  
  ## Exception
```
/flutter ( 6592): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6592): The following assertion was thrown building ExtendedNavigator<Router>(state:
I/flutter ( 6592): ExtendedNavigatorState<Router>#72ed2):
I/flutter ( 6592): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2725 pos 14:
I/flutter ( 6592): 'observer.navigator == null': is not true.
I/flutter ( 6592):
I/flutter ( 6592): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6592): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6592): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6592):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 6592):
I/flutter ( 6592): The relevant error-causing widget was:
I/flutter ( 6592):   ExtendedNavigator<Router> 
lib\main.dart:135
I/flutter ( 6592):
I/flutter ( 6592): When the exception was thrown, this was the stack:
I/flutter ( 6592): #2      NavigatorState.initState 
package:flutter/…/widgets/navigator.dart:2725
I/flutter ( 6592): #3      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4684
I/flutter ( 6592): #4      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4520
I/flutter ( 6592): ...     Normal element mounting (215 frames)
I/flutter ( 6592): #219    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3490
I/flutter ( 6592): #220    Element.updateChild 
package:flutter/…/widgets/framework.dart:3258
I/flutter ( 6592): #221    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 6592): #222    _InheritedProviderScopeElement.performRebuild 
package:provider/src/inherited_provider.dart:426
I/flutter ( 6592): #223    Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 6592): #224    ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4525
I/flutter ( 6592): #225    ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4520
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #232    SingleChildWidgetElementMixin.mount 
package:nested/nested.dart:223
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #239    _NestedHookElement.mount 
package:nested/nested.dart:188
I/flutter ( 6592): #240    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3490
I/flutter ( 6592): #241    Element.updateChild 
package:flutter/…/widgets/framework.dart:3258
I/flutter ( 6592): #242    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 6592): #243    _InheritedProviderScopeElement.performRebuild 
package:provider/src/inherited_provider.dart:426
I/flutter ( 6592): #244    Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 6592): #245    ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4525
I/flutter ( 6592): #246    ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4520
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #253    SingleChildWidgetElementMixin.mount 
package:nested/nested.dart:223
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #260    _NestedHookElement.mount 
package:nested/nested.dart:188
I/flutter ( 6592): #261    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3490
I/flutter ( 6592): #262    Element.updateChild 
package:flutter/…/widgets/framework.dart:3258
I/flutter ( 6592): #263    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 6592): #264    _InheritedProviderScopeElement.performRebuild 
package:provider/s
I/flutter ( 6592): #265    Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 6592): #266    ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4525
I/flutter ( 6592): #267    ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4520
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #274    SingleChildWidgetElementMixin.mount 
package:nested/nested.dart:223
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #281    _NestedHookElement.mount 
package:nested/nested.dart:188
I/flutter ( 6592): #282    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3490
I/flutter ( 6592): #283    Element.updateChild 
package:flutter/…/widgets/framework.dart:3258
I/flutter ( 6592): #284    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 6592): #285    _InheritedProviderScopeElement.performRebuild 
package:provider/src/inherited_provider.dart:426
I/flutter ( 6592): #286    Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 6592): #287    ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4525
I/flutter ( 6592): #288    ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4520
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #295    SingleChildWidgetElementMixin.mount 
package:nested/nested.dart:223
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #302    _NestedHookElement.mount 
package:nested/nested.dart:188
I/flutter ( 6592): #303    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3490
I/flutter ( 6592): #304    Element.updateChild 
package:flutter/…/widgets/framework.dart:3258
I/flutter ( 6592): #305    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 6592): #306    _InheritedProviderScopeElement.performRebuild 
package:provider/src/inherited_provider.dart:426
I/flutter ( 6592): #307    Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 6592): #308    ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4525
I/flutter ( 6592): #309    ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4520
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #316    SingleChildWidgetElementMixin.mount 
package:nested/nested.dart:223
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #323    _NestedHookElement.mount 
package:nested/nested.dart:188
I/flutter ( 6592): #324    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3490
I/flutter ( 6592): #325    Element.updateChild 
package:flutter/…/widgets/framework.dart:3258
I/flutter ( 6592): #326    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 6592): #327    _InheritedProviderScopeElement.performRebuild 
package:provider/src/inherited_provider.dart:426
I/flutter ( 6592): #328    Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 6592): #329    ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4525
I/flutter ( 6592): #330    ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4520
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #337    SingleChildWidgetElementMixin.mount 
package:nested/nested.dart:223
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #344    _NestedHookElement.mount 
package:nested/nested.dart:188
I/flutter ( 6592): #345    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3490
I/flutter ( 6592): #346    Element.updateChild 
package:flutter/…/widgets/framework.dart:3258
I/flutter ( 6592): #347    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 6592): #348    _InheritedProviderScopeElement.performRebuild 
package:provider/src/inherited_provider.dart:426
I/flutter ( 6592): #349    Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 6592): #350    ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4525
I/flutter ( 6592): #351    ComponentElement.mount 
package:flutter/…/
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #358    SingleChildWidgetElementMixin.mount 
package:nested/nested.dart:223
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #365    _NestedHookElement.mount 
package:nested/nested.dart:188
I/flutter ( 6592): #366    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3490
I/flutter ( 6592): #367    Element.updateChild 
package:flutter/…/widgets/framework.dart:3258
I/flutter ( 6592): #368    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 6592): #369    _InheritedProviderScopeElement.performRebuild 
package:provider/src/inherited_provider.dart:426
I/flutter ( 6592): #370    Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 6592): #371    ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4525
I/flutter ( 6592): #372    ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4520
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #379    SingleChildWidgetElementMixin.mount 
package:nested/nested.dart:223
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #386    _NestedHookElement.mount 
package:nested/nested.dart:188
I/flutter ( 6592): #387    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3490
I/flutter ( 6592): #388    Element.updateChild 
package:flutter/…/widgets/framework.dart:3258
I/flutter ( 6592): #389    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 6592): #390    _InheritedProviderScopeElement.performRebuild 
package:provider/src/inherited_provider.dart:426
I/flutter ( 6592): #391    Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 6592): #392    ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4525
I/flutter ( 6592): #393    ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4520
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #400    SingleChildWidgetElementMixin.mount 
package:nested/nested.dart:223
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #407    _NestedHookElement.mount 
package:nested/nested.dart:188
I/flutter ( 6592): ...     Normal element mounting (7 frames)
I/flutter ( 6592): #414    SingleChildWidgetElementMixin.mount 
package:nested/nested.dart:223
I/flutter ( 6592): #415    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3490
I/flutter ( 6592): #416    Element.updateChild 
package:flutter/…/widgets/framework.dart:3255
I/flutter ( 6592): #417    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4571
I/flutter ( 6592): #418    StatefulElement.performRebuild 
package:flutter/…/widgets/framework.dart:4719
I/flutter ( 6592): #419    Element.rebuild 
package:flutter/…/widgets/framework.dart:4262
I/flutter ( 6592): #420    BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2667
I/flutter ( 6592): #421    WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:866
I/flutter ( 6592): #422    RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:286
I/flutter ( 6592): #423    SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1117
I/flutter ( 6592): #424    SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1056
I/flutter ( 6592): #425    SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:972
I/flutter ( 6592): #429    _invoke  (dart:ui/hooks.dart:253:10)
I/flutter ( 6592): #430    _drawFrame  (dart:ui/hooks.dart:211:3)
I/flutter ( 6592): (elided 5 frames from class _AssertionError and dart:async)
I/flutter ( 6592):
```
</details>

Do you have any idea how this could work?

**Comment by Milad-Akarie** [comment]
ExtendedNavigater(
....,
Observers:[<YOUR OBSERVERS GO HERE>]
),

**Comment by sceee** [comment]
@Milad-Akarie thanks for the fast response but... this would then be like I wrote above in the first code snipped, right? And this also leads to the exception.

**Comment by Milad-Akarie** [comment]
Remove any thing navigation related from MaterialApp including
navigaterObservers

**Comment by sceee** [comment]
Even with this, it does unfortunately not work:
```
return MaterialApp(
            builder: ExtendedNavigator<Router>(
              router: Router(),
              observers: [observer],
            ),
          );
```

**Comment by jorgelrj** [comment]
> Even with this, it does unfortunately not work:
> 
> ```
> return MaterialApp(
>             builder: ExtendedNavigator<Router>(
>               router: Router(),
>               observers: [observer],
>             ),
>           );
> ```

@sceee try to use it with `ExtendedNavigator.builder`

**Comment by sceee** [comment]
Cool, works @jorgelrj 👏 

Thank you very much for your help!!

**Comment by rignaneseleo** [comment]
Any update on this for the last version?

**Comment by Milad-Akarie** [comment]
@rignaneseleo refer to this https://pub.dev/packages/auto_route#navigation-observers
