### ISSUE TITLE
Calling router independently from context

### ISSUE THREAD

**Issue by filipeteotonio** [Milad-Akarie/auto_route_library#342]
This is more of a question rather than an issue. As in previous versions, we could call the Router without any reference to the BuildContext. Is there a way to achieve this in the current version? If not, is there a reason for that?

**Comment by Milad-Akarie** [comment]
@filipeteotonio The Generated router it self is a the routing controller, you can inject it or define it as a global variable and use it without context.

**Comment by theweiweiway** [comment]
closing due to
- stale issue
- answer provided

**Comment by easazade** [comment]
I tried this and it did not work: 
```dart
var router = AppRouter();
```

I got this error 

```
E/flutter ( 9416): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:auto_route/src/router/controller/routing_controller.dart': Failed assertion: line 456 pos 12: '_pages.isNotEmpty': is not true.
E/flutter ( 9416): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 9416): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 9416): #2      BranchEntry.replace (package:auto_route/src/router/controller/routing_controller.dart:456:12)
E/flutter ( 9416): #3      RootStackRouter.replace (package:auto_route/src/router/root_stack_router.dart:152:20)
E/flutter ( 9416): #4      _State.initState.<anonymous closure> (package:talan/screens/splash/splash_screen.dart:23:16)
E/flutter ( 9416): #5      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter ( 9416): #6      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 9416): #7      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
E/flutter ( 9416): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
E/flutter ( 9416): #9      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
E/flutter ( 9416): #10     Future._complete (dart:async/future_impl.dart:530:7)
E/flutter ( 9416): #11     new Future.delayed.<anonymous closure> (dart:async/future.dart:312:16)
E/flutter ( 9416): #12     _rootRun (dart:async/zone.dart:1346:47)
E/flutter ( 9416): #13     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 9416): #14     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter ( 9416): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter ( 9416): #16     _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 9416): #17     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 9416): #18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
E/flutter ( 9416): #19     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 9416): #20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter ( 9416): #21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter ( 9416): #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
