### ISSUE TITLE
AutoRout crash

### ISSUE THREAD

**Issue by mbmshafraz** [Milad-Akarie/auto_route_library#417]
This is my router.dart code

```
@MaterialAutoRouter(
    replaceInRouteName: 'Page,Route',
    routes:<AutoRoute>[
    AutoRoute(page: HomePage, name: 'home', initial: true),
    AutoRoute(page: WeatherPage, name: 'weather')
  ]
)

class 

> $Router{}
```

```
This is my main.dart code

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: Conf.appName,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: SafeArea(
        child: Root(),
      ),
    );
  }
}

class Root extends StatefulWidget {
  @override
  _RootState createState() => _RootState();
}

class _RootState extends State<Root> {
  @override
  Widget build(BuildContext context) {
    AutoRouter.of(context);
    return Scaffold(
      body: AutoRouter(),
    );
  }
}
```

I see this following error 

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Root(dirty, state: _RootState#48e31):
AutoRouter operation requested with a context that does not include an AutoRouter.

The context used to retrieve the Router must be that of a widget that is a descendant of an AutoRouter widget.
The relevant error-causing widget was: 
  Root file:///Volumes/Data/Projects/Paul/WreckFinder/wreckfinder/lib/main.dart:22:16
When the exception was thrown, this was the stack: 
#0      AutoRouter.of.<anonymous closure> (package:auto_route/src/router/widgets/auto_router.dart:43:9)
#1      AutoRouter.of (package:auto_route/src/router/widgets/auto_router.dart:49:6)
#2      _RootState.build (package:wreckfinder/main.dart:36:16)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
...
====================================================================================================
```

I am wondering whether problem with my code or some bugs are there in library

**Comment by theweiweiway** [comment]
Hi, I'm assuming you are using version 1.0.x

You need to use `MaterialApp.router`, not `MaterialApp`. Check out the docs here for installation and setup: https://autoroute.vercel.app/introduction/installation_and_usage

**Comment by theweiweiway** [comment]
Closing due to stale issue

**Comment by harsh2338** [comment]
@theweiweiway i used  MaterialApp.router but I have the same issue. here is the link to my [issue](https://stackoverflow.com/questions/67530581/how-to-fix-autorouter-operation-requested-with-a-context-that-does-not-include)
