### ISSUE TITLE
How to define an initial route with a parameter (ex. "/:id")?

### ISSUE THREAD

**Issue by jbt-cii** [Milad-Akarie/auto_route_library#446]
I would like to define the initial route to a page accepting a parameter.
I found the way to do that when it isn't the initial page like this:
```dart
AutoRouter.of(context).pushPath("/Page/:123");
```

But if it is the initial page I get this error:
```
E/flutter ( 6689): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Can not resolve initial route
E/flutter ( 6689): #0      RootRouterDelegate.setInitialRoutePath
package:auto_route/…/widgets/auto_router_delegate.dart:74
E/flutter ( 6689): #1      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter ( 6689): #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
```

This is my code:
```dart
class Application extends StatefulWidget {
  @override
  ApplicationState createState() => ApplicationState();
}

class ApplicationState extends State<Application> {
  final _appRouter = AppRouter();

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
...
      builder: () => MaterialApp(
...
        home: MaterialApp.router(
          debugShowCheckedModeBanner: false,
          routeInformationParser: _appRouter.defaultRouteParser(),
          routerDelegate: _appRouter.delegate(),
        ),
      ),
    );
  }
}
```

In my "router.dart" file:

```dart
import 'package:auto_route/auto_route.dart';
...

@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    CustomRoute(path: "/:id", initial: true, page: MyPage, transitionsBuilder: TransitionsBuilders.fadeIn),
    CustomRoute(path: "/second", page: MySecondPage, transitionsBuilder: TransitionsBuilders.fadeIn),
  ],
)
class $AppRouter {}
```

I work with "Flutter 2" with channel "master":
```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.323, on macOS 11.2.1 20D74 darwin-arm, locale fr-FR)
    • Flutter version 2.1.0-13.0.pre.323 at /opt/homebrew/Caskroom/flutter/1.22.6/flutter
    • Framework revision 2cdd51900c (3 days ago), 2021-03-30 10:16:05 +0200
    • Engine revision dbcbf69a57
    • Dart version 2.13.0 (build 2.13.0-175.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ciitelecom/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

I declared my first page like this:

```dart
class MyPage extends StatelessWidget {
  final int? id;

  const MyPage({@PathParam('id') this.id = 0}) : super();
  
  ...
}
```

My "id" variable should get "0" by default.
I think the problem come from the "default" parameter to give to the initial page.
I can't find a way to give "0" for example by default to the initial call.

Thanks for any help.

**Comment by Milad-Akarie** [comment]
Hey @jbt-cii I believe your page path should be '/page/:id'.
if you can obtain the path before the App runs you could just pass it to 
`_appRouter.delegate(initialDeepLink: '/page/123');`
if you wanna do it inside of a deeplink listeners for example you could use pushPath('/page/123') without the colon before the id;

**Comment by jbt-cii** [comment]
Hello @Milad-Akarie 
Exactly what I needed!
In my example it works with that:

```
routerDelegate: _appRouter.delegate(initialDeepLink: '/0'),
```

Thanks a lot!
