### ISSUE TITLE
How do I use this with device_preview?

### ISSUE THREAD

**Issue by claudiaaw** [Milad-Akarie/auto_route_library#580]
I am trying to use device_preview like this with auto_route where I have to add a builder and a locale:
  
```
   final _appRouter = AppRouter()  
   ...  
  Widget build(BuildContext context){  
      return MaterialApp.router(  
             routerDelegate: _appRouter.delegate(...initialConfig),  
             routeInformationParser: _appRouter.defaultRouteParser(),  
             locale: DevicePreview.locale(context),
             builder: DevicePreview.appBuilder,
         ),  
  }  
```

But when I run the app I am getting the following error:

```
E/flutter (19648): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'Future<Object>' in type cast
E/flutter (19648): #0      _RouterState._verifyRouteInformationParserStillCurrent.<anonymous closure>
package:flutter/…/widgets/router.dart:633
E/flutter (19648): #1      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (19648): #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (19648): #3      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
E/flutter (19648): #5      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
E/flutter (19648): #6      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:403:9)
E/flutter (19648): #7      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (19648): #8      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (19648): #9      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (19648): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (19648): #11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (19648): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

How do I go about fixing this issue since it is identifying an issue in the auto_route's router.dart file? If I am using the library wrongly or if I should be posting this issue under device_preview then please let me know thanks!

**Comment by cfregin** [comment]
Have you tried:

```dart
builder: (context, router) => DevicePreview.appBuilder(context, router),
```
?

**Comment by claudiaaw** [comment]
@cfregin I just tried it and I am still getting the same error!

**Comment by alvindrakes** [comment]
Having the same **type 'Future<dynamic>' unhandled exception** issue. 

This is my code setup for auto router and device preview. 


```
child: MaterialApp.router(
            title: 'Supagreen',
            builder: (context, widget) {
              return MediaQuery(
                //For flutter_screenutil font setup
                //font does not change with system font size
                data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                //device preview setup
                child: DevicePreview.appBuilder(context, widget!),
              );
            },
            locale: DevicePreview.locale(context),

            //auto route setup
            routerDelegate: _appRouter.delegate(),
            routeInformationParser: _appRouter.defaultRouteParser(),
            
```

**Comment by yarmat** [comment]
I faced with the same exception but I don't use device_preview

This is my setup: 
```
ScreenUtilInit(
      designSize: Size(Constants.baseWidth, Constants.baseHeight),
      builder: () => MaterialApp.router(
        builder: (BuildContext context, Widget? widget) {
          registerContext(context);
          return botToastBuilder(context, widget);
        },
        localizationsDelegates: context.localizationDelegates,
        supportedLocales: context.supportedLocales,
        locale: localizationService.locale,
        debugShowCheckedModeBanner: false,
        title: DotEnv.env['APP_NAME']!,
        routerDelegate: _appRouter.delegate(),
        routeInformationParser: _appRouter.defaultRouteParser(),
        theme: theme(context),
      ),
    );
```

And my exception:
```
E/flutter ( 9959): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'Future<Object>' in type cast
E/flutter ( 9959): #0      _RouterState._verifyRouteInformationParserStillCurrent.<anonymous closure> (package:flutter/src/widgets/router.dart:633:21)
E/flutter ( 9959): #1      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter ( 9959): #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 9959): #3      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
E/flutter ( 9959): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
E/flutter ( 9959): #5      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
E/flutter ( 9959): #6      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:403:9)
E/flutter ( 9959): #7      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 9959): #8      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 9959): #9      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter ( 9959): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter ( 9959): #11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 9959): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by spakanati** [comment]
I'm seeing the same exception, with or without device_preview included. So far I've noticed that the error seems to occur only on hot restart (i.e. using the green restart arrow in VSCode as opposed to the automatic hot reload).

**Comment by yarmat** [comment]
In my case, this exception thrown when I used easy_localization package - https://github.com/aissat/easy_localization/issues/329

**Comment by xalikoutis** [comment]
same problem here when i am using device_preview
