### ISSUE TITLE
Firebase Analytics + GlobalKey was used multiple times error

### ISSUE THREAD

**Issue by brendanwanlass** [Milad-Akarie/auto_route_library#693]
Hi, I've been able to get AutoRoute working fine but when I went to add a navigator observer, I started getting errors:

```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building AutoRouteNavigator(state: _AutoRouteNavigatorState#065f3):
type 'List<NavigatorObserver>' is not a subtype of type 'List<FirebaseAnalyticsObserver>' of 'other'

The relevant error-causing widget was: 
  AutoRouteNavigator file:///Users/brendanwanlass/Code/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-2.3.0/lib/src/router/widgets/auto_router_delegate.dart:134:16
When the exception was thrown, this was the stack: 
#0      ListMixin.+ (dart:collection/list.dart)
#1      NavigatorState._updateEffectiveObservers (package:flutter/src/widgets/navigator.dart:3544:46)
#2      NavigatorState._updateHeroController (package:flutter/src/widgets/navigator.dart:3538:7)
#3      NavigatorState.initState (package:flutter/src/widgets/navigator.dart:3395:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4711:57)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building AutoRouteNavigator(state: _AutoRouteNavigatorState#065f3):
A GlobalKey was used multiple times inside one widget's child list.

The offending GlobalKey was: [LabeledGlobalKey<NavigatorState>#892c6]
The parent of the widgets with that key was: AutoRouteNavigator
  state: _AutoRouteNavigatorState#065f3
The first child to get instantiated with that key became: Navigator-[LabeledGlobalKey<NavigatorState>#892c6]
  dirty
  state: NavigatorState#76f2e(lifecycle state: created)
The second child that was to be instantiated with that key was: AutoRouteNavigator
A GlobalKey can only be specified on one widget at a time in the widget tree.
The relevant error-causing widget was: 
  AutoRouteNavigator file:///Users/brendanwanlass/Code/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-2.3.0/lib/src/router/widgets/auto_router_delegate.dart:134:16
When the exception was thrown, this was the stack: 
#0      Element._retakeInactiveElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:3548:11)
#1      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3562:8)
#2      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3593:33)
#3      Element.updateChild (package:flutter/src/widgets/framework.dart:3360:20)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
...
====================================================================================================
```

Here is my Material App:
```
  Widget build(BuildContext context) {
    return MaterialApp.router(
      theme: MangoThemeData.lightTheme,
      debugShowCheckedModeBanner: false,
      routerDelegate: router.delegate(
        navigatorObservers: () => [
          FirebaseAnalyticsObserver(analytics: FirebaseAnalytics())
        ]
      ),
      routeInformationParser: router.defaultRouteParser(),
      builder: (_, router) {
        return SafeArea(
          child: router!
        );
      }
    );
  }
  ```
  
  The offending change is this:
  ```
      navigatorObservers: () => [
        FirebaseAnalyticsObserver(analytics: FirebaseAnalytics())
      ]
 ```

**Comment by Milad-Akarie** [comment]
That's weird, try this: 
```dart
   navigatorObservers: () => <NavigatorObserver>[
      FirebaseAnalyticsObserver(analytics: FirebaseAnalytics())
    ]
```

**Comment by brendanwanlass** [comment]
That worked; thank you.
