### ISSUE TITLE
Unhandled Exception: Bad state: Future already completed

### ISSUE THREAD

**Issue by wim07101993** [Milad-Akarie/auto_route_library#729]
I have a few screens: 
- Nested: contains a nested router
- Fowarder: immediatly pushes SomeForm
- SomeForm: would contain a form or something like that
- Finish: gives the choice to start the flow again

When I do the following flow, a `Unhandled Exception: Bad state: Future already completed` happens.
```
                      I/flutter (31203): Push to _placeHolder_
                      I/flutter (31203): Push from _placeHolder_ to ForwarderRoute
                      I/flutter (31203): Remove to _placeHolder_
                      I/flutter (31203): Push from ForwarderRoute to SomeFormRoute
Navigate back ->      I/flutter (31203): Pop from ForwarderRoute to SomeFormRoute
Press next button ->  I/flutter (31203): Next button pressed
                      I/flutter (31203): Push from ForwarderRoute to FinishRoute
Press again button -> I/flutter (31203): Again button pressed
                      I/flutter (31203): Push from FinishRoute to ForwarderRoute
                      I/flutter (31203): Remove from ForwarderRoute to FinishRoute
                      I/flutter (31203): Push from ForwarderRoute to ForwarderRoute
                      I/flutter (31203): Push from ForwarderRoute to SomeFormRoute
                      I/flutter (31203): Remove from ForwarderRoute to ForwarderRoute
                      I/flutter (31203): Push from ForwarderRoute to ForwarderRoute
                      I/flutter (31203): Push from ForwarderRoute to SomeFormRoute
                      I/flutter (31203): Remove from ForwarderRoute to ForwarderRoute
                      E/flutter (31203): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future already completed
                      E/flutter (31203): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
                      E/flutter (31203): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
                      E/flutter (31203): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
                      E/flutter (31203): <asynchronous suspension>
                      E/flutter (31203): 
                      I/flutter (31203): Push from ForwarderRoute to ForwarderRoute
                      I/flutter (31203): Push from ForwarderRoute to SomeFormRoute
                      I/flutter (31203): Remove from ForwarderRoute to ForwarderRoute
                      E/flutter (31203): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future already completed
                      E/flutter (31203): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
                      E/flutter (31203): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
                      E/flutter (31203): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
                      E/flutter (31203): <asynchronous suspension>
                      E/flutter (31203): 
                      I/flutter (31203): Push from ForwarderRoute to ForwarderRoute
                      I/flutter (31203): Push from ForwarderRoute to SomeFormRoute
                      I/flutter (31203): Remove from ForwarderRoute to ForwarderRoute
                      E/flutter (31203): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future already completed
                      E/flutter (31203): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
                      E/flutter (31203): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
                      E/flutter (31203): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
                      E/flutter (31203): <asynchronous suspension>
                      E/flutter (31203): 
                      I/flutter (31203): Push from ForwarderRoute to ForwarderRoute
                      I/flutter (31203): Push from ForwarderRoute to SomeFormRoute
                      I/flutter (31203): Remove from ForwarderRoute to ForwarderRoute
                      E/flutter (31203): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future already completed
                      E/flutter (31203): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
                      E/flutter (31203): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
                      E/flutter (31203): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
                      E/flutter (31203): <asynchronous suspension>
                      E/flutter (31203): 
                      I/flutter (31203): Push from ForwarderRoute to ForwarderRoute
                      I/flutter (31203): Push from ForwarderRoute to SomeFormRoute
                      I/flutter (31203): Remove from ForwarderRoute to ForwarderRoute
                      E/flutter (31203): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future already completed
                      E/flutter (31203): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
                      E/flutter (31203): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
                      E/flutter (31203): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
                      E/flutter (31203): <asynchronous suspension>
                      E/flutter (31203): 
                      I/flutter (31203): Push from SomeFormRoute to SomeFormRoute
```

<details>

# Source code

```dart
import 'package:auto_route/annotations.dart';
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';

import 'main.gr.dart';

void main() {
  runApp(App());
}

class App extends StatefulWidget {
  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  final AppRouter _router = AppRouter();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: _router.delegate(initialRoutes: [
        const NestedRoute(),
      ]),
      routeInformationParser: _router.defaultRouteParser(),
    );
  }
}

class Nested extends StatefulWidget {
  @override
  State<Nested> createState() => _NestedState();
}

class _NestedState extends State<Nested> {
  @override
  Widget build(BuildContext context) {
    return AutoRouter(
      navigatorObservers: () => [NavigationListener()],
    );
  }
}

class Forwarder extends StatefulWidget {
  @override
  State<Forwarder> createState() => _ForwarderState();
}

class _ForwarderState extends State<Forwarder> {
  @override
  void initState() {
    super.initState();
    context.pushRoute(const SomeFormRoute());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: ElevatedButton(
              onPressed: () {
                print('Next button pressed');
                context.pushRoute(const FinishRoute());
              },
              child: const Text("Next"),
            ),
          )
        ],
      ),
    );
  }
}

class SomeForm extends StatelessWidget {
  @override
  Widget build(BuildContext context) => const Text("Some Form");
}

class Finish extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: ElevatedButton(
              onPressed: () {
                print('Again button pressed');
                context.replaceRoute(const ForwarderRoute());
              },
              child: const Text("Again"),
            ),
          )
        ],
      ),
    );
  }
}

@MaterialAutoRouter(
  routes: [
    AutoRoute(
      page: Nested,
      children: [
        AutoRoute(path: '', page: Forwarder),
        AutoRoute(page: SomeForm),
        AutoRoute(page: Finish),
      ],
    ),
  ],
)
class $AppRouter {}

class NavigationListener extends AutoRouterObserver {
  @override
  void didChangeTabRoute(TabPageRoute route, TabPageRoute previousRoute) {
    _log("Changed tab route", route.name, previousRoute.name);
  }

  @override
  void didInitTabRoute(TabPageRoute route, TabPageRoute? previousRoute) {
    _log("Init tab route", route.name, previousRoute?.name);
  }

  @override
  void didPop(Route route, Route? previousRoute) {
    _log("Pop", route.settings.name, previousRoute?.settings.name);
  }

  @override
  void didPush(Route route, Route? previousRoute) {
    _log("Push", route.settings.name, previousRoute?.settings.name);
  }

  @override
  void didRemove(Route route, Route? previousRoute) {
    _log("Remove", route.settings.name, previousRoute?.settings.name);
  }

  @override
  void didReplace({Route? newRoute, Route? oldRoute}) {
    _log("Replace", newRoute?.settings.name, oldRoute?.settings.name);
  }

  @override
  void didStartUserGesture(Route route, Route? previousRoute) {
    _log(
        "Start userGesture", route.settings.name, previousRoute?.settings.name);
  }

  @override
  void didStopUserGesture() {
    _log("Stop user gesture", null, null);
  }

  void _log(String action, String? routeName, String? previousRouteName) {
    if (routeName == null && previousRouteName == null) {
      print(action);
    } else if (routeName == null) {
      print("$action from $previousRouteName");
    } else if (previousRouteName == null) {
      print("$action to $routeName");
    } else {
      print("$action from $previousRouteName to $routeName");
    }
  }
}
```

# flutter run -v

```
[ +115 ms] --------- beginning of main
                    09-30 13:59:51.711 I/Finsky  (30184): [2] nsq.M(18): Installer: Notifying status update.
                    package=be.modero.roger, status=UNINSTALLED
[   +6 ms] executing: C:\Users\wvl\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0B211JEC200481 shell am start -a
android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true be.modero.roger/be.modero.roger.MainActivity
[ +117 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=be.modero.roger/.MainActivity (has
extras) }
[   +1 ms] Waiting for observatory port to be available...
[+1042 ms] W/FlutterActivityAndFragmentDelegate(31877): A splash screen was provided to Flutter, but this is deprecated.
See flutter.dev/go/android-splash-migration for migration steps.
[ +102 ms] Observatory URL on device: http://127.0.0.1:42597/fbY21fpMvbo=/
[   +1 ms] executing: C:\Users\wvl\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0B211JEC200481 forward tcp:0
tcp:42597
[  +28 ms] 63489
[        ] Forwarded host port 63489 to device port 42597 for Observatory
[   +4 ms] Caching compiled dill
[  +22 ms] Connecting to service protocol: http://127.0.0.1:63489/fbY21fpMvbo=/
[ +211 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:63489/fbY21fpMvbo=/.
[ +176 ms] DDS is listening at http://127.0.0.1:63492/AmBFcZPI3mw=/.
[  +50 ms] Successfully connected to service protocol: http://127.0.0.1:63489/fbY21fpMvbo=/
[  +70 ms] DevFS: Creating new filesystem on the device (null)
[  +31 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/be.modero.roger/code_cache/sandboxRLGBWQ/sandbox/)
[   +2 ms] Updating assets
[  +90 ms] Syncing files to device Pixel 4a...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:sandbox/main.dart 623a70f5-ce0b-48b3-adc3-44ed2cedff2d
[        ] <- 623a70f5-ce0b-48b3-adc3-44ed2cedff2d
[  +87 ms] Updating files.
[        ] DevFS: Sync finished
[   +2 ms] Syncing files to device Pixel 4a... (completed in 95ms)
[   +1 ms] Synced 0.0MB.
[   +1 ms] <- accept
[   +8 ms] Connected to _flutterView/0xb40000711b26cec0.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[   +1 ms] An Observatory debugger and profiler on Pixel 4a is available at: http://127.0.0.1:63492/AmBFcZPI3mw=/
[ +140 ms] DevTools activation throttled until 2021-09-30 22:44:24.607807.
[ +136 ms] I/flutter (31877): Push to _placeHolder_
[ +178 ms] I/flutter (31877): Push from _placeHolder_ to ForwarderRoute
[        ] I/flutter (31877): Remove to _placeHolder_
[ +310 ms] I/flutter (31877): Push from ForwarderRoute to SomeFormRoute
[  +34 ms] The Flutter DevTools debugger and profiler on Pixel 4a is available at:
           http://127.0.0.1:63597?uri=http://127.0.0.1:63492/AmBFcZPI3mw=/
[+5251 ms] I/flutter (31877): Pop from ForwarderRoute to SomeFormRoute
[+1285 ms] I/flutter (31877): Next button pressed
[   +8 ms] I/flutter (31877): Push from ForwarderRoute to FinishRoute
[+1178 ms] I/flutter (31877): Again button pressed
[  +11 ms] I/flutter (31877): Push from FinishRoute to ForwarderRoute
[   +1 ms] I/flutter (31877): Remove from ForwarderRoute to FinishRoute
[  +53 ms] I/flutter (31877): Push from ForwarderRoute to ForwarderRoute
[   +1 ms] I/flutter (31877): Push from ForwarderRoute to SomeFormRoute
[   +1 ms] I/flutter (31877): Remove from ForwarderRoute to ForwarderRoute
[  +41 ms] I/flutter (31877): Push from ForwarderRoute to ForwarderRoute
[   +1 ms] I/flutter (31877): Push from ForwarderRoute to SomeFormRoute
[   +1 ms] I/flutter (31877): Remove from ForwarderRoute to ForwarderRoute
[  +31 ms] E/flutter (31877): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future
already completed
[   +1 ms] E/flutter (31877): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
[   +1 ms] E/flutter (31877): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
[   +1 ms] E/flutter (31877): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[        ] E/flutter (31877): <asynchronous suspension>
[        ] E/flutter (31877):
[  +13 ms] I/flutter (31877): Push from ForwarderRoute to ForwarderRoute
[   +1 ms] I/flutter (31877): Push from ForwarderRoute to SomeFormRoute
[        ] I/flutter (31877): Remove from ForwarderRoute to ForwarderRoute
[  +35 ms] E/flutter (31877): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future
already completed
[   +1 ms] E/flutter (31877): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
[   +1 ms] E/flutter (31877): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
[        ] E/flutter (31877): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[        ] E/flutter (31877): <asynchronous suspension>
[        ] E/flutter (31877):
[   +3 ms] I/flutter (31877): Push from ForwarderRoute to ForwarderRoute
[   +1 ms] I/flutter (31877): Push from ForwarderRoute to SomeFormRoute
[   +1 ms] I/flutter (31877): Remove from ForwarderRoute to ForwarderRoute
[  +37 ms] E/flutter (31877): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future
already completed
[   +1 ms] E/flutter (31877): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
[   +1 ms] E/flutter (31877): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
[   +1 ms] E/flutter (31877): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[   +1 ms] E/flutter (31877): <asynchronous suspension>
[        ] E/flutter (31877):
[   +3 ms] I/flutter (31877): Push from ForwarderRoute to ForwarderRoute
[        ] I/flutter (31877): Push from ForwarderRoute to SomeFormRoute
[   +1 ms] I/flutter (31877): Remove from ForwarderRoute to ForwarderRoute
[  +39 ms] E/flutter (31877): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future
already completed
[   +1 ms] E/flutter (31877): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
[   +1 ms] E/flutter (31877): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
[   +1 ms] E/flutter (31877): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[        ] E/flutter (31877): <asynchronous suspension>
[        ] E/flutter (31877):
[   +1 ms] I/flutter (31877): Push from ForwarderRoute to ForwarderRoute
[        ] I/flutter (31877): Push from ForwarderRoute to SomeFormRoute
[        ] I/flutter (31877): Remove from ForwarderRoute to ForwarderRoute
[  +40 ms] E/flutter (31877): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future
already completed
[   +1 ms] E/flutter (31877): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
[   +1 ms] E/flutter (31877): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
[   +1 ms] E/flutter (31877): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[        ] E/flutter (31877): <asynchronous suspension>
[        ] E/flutter (31877):
[   +5 ms] I/flutter (31877): Push from ForwarderRoute to ForwarderRoute
[   +1 ms] I/flutter (31877): Push from ForwarderRoute to SomeFormRoute
[   +1 ms] I/flutter (31877): Remove from ForwarderRoute to ForwarderRoute
[  +61 ms] E/flutter (31877): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future
already completed
[   +1 ms] E/flutter (31877): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
[        ] E/flutter (31877): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
[   +1 ms] E/flutter (31877): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[   +1 ms] E/flutter (31877): <asynchronous suspension>
[   +1 ms] E/flutter (31877):
[  +34 ms] I/flutter (31877): Push from SomeFormRoute to SomeFormRoute
```

# flutter doctor -v

```
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale en-BE)
    • Flutter version 2.5.1 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\wvl\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5486

[✓] VS Code, 64-bit edition (version 1.60.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Pixel 4a (mobile) • 0B211JEC200481 • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.19043.1237]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 94.0.992.31

• No issues found!
```
</details>

**Comment by wim07101993** [comment]
This is a workaround. However it is dirty...

```dart
final router = context.router;
final currentRoute = router.current;
router.push(const ForwarderRoute());
Future.delayed(const Duration(seconds: 2))
    .then((_) => router.removeRoute(currentRoute));
```

**Comment by Milad-Akarie** [comment]
@wim07101993 when does the exception happen? 
als calling context.pushRoute inside of initState is not a good idea.

**Comment by wim07101993** [comment]
I'm not able to debug it very good. But my guess:
When on the FinisheRoute, the again button is pressed, it calls the replaceRoute. this (I think) internally calls a push and remove. But it does a push and I think the Forwarder route pushes another screen before the remove has happened. Then some funky stuff happens as you can see in the logs. I don't know what the exact flow is since I do not know the inner workings of the AutoRouter.

I know calling the router from initState is a bad idea but it simulates a case I have in an actual app ;)
