### ISSUE TITLE
Router can not navigate to ...[About Nested navigation]

### ISSUE THREAD

**Issue by tmxdyf** [Milad-Akarie/auto_route_library#742]
Router :
```dart
@MaterialAutoRouter(replaceInRouteName: 'Page,Route', routes: <AutoRoute>[
  CustomRoute(
    page: GenerateQRCodePage,
    children: [
      CustomRoute(
        page: ResultQRCodePage,
        transitionsBuilder: TransitionsBuilders.slideBottom,
      ),
    ],
  ),
])
class $AppRouter {}
```
push:
```dart

class _GenerateQRCodePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final generateBtnWidget =
        BlocBuilder<GenerateQRCodeCubit, GenerateQRCodeState>(
      builder: (context, state) {
        if (state.isVisibilityGenerateBtn) {
          return IconButton(
            onPressed: () {
              ResultQRCodeRoute().show(context);///push
            },
            icon: Icon(Icons.qr_code_2_outlined),
          );
        }
        return SizedBox();
      },
    );
.......
```

Crash :
```
/flutter (24157): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [Root Router] Router can not navigate to result-qr-code-page
E/flutter (24157): #0      RoutingController._matchOrReportFailure (package:auto_route/src/router/controller/routing_controller.dart:77:9)
E/flutter (24157): #1      StackRouter._push (package:auto_route/src/router/controller/routing_controller.dart:722:17)
E/flutter (24157): #2      StackRouter.push (package:auto_route/src/router/controller/routing_controller.dart:672:35)
E/flutter (24157): #3      PageRouteInfo.show (package:auto_route/src/route/page_route_info.dart:122:27)
E/flutter (24157): #4      GenerateQRCodeCubit.onGenerateQRCodePressed (package:micro_tools/pages/qrcode/generate_qr_code_cubit.dart:63:25)
E/flutter (24157): #5      _GenerateQRCodePage.build.<anonymous closure>.<anonymous closure> (package:micro_tools/pages/qrcode/generate_qr_code_page.dart:43:22)
E/flutter (24157): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
E/flutter (24157): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
E/flutter (24157): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
E/flutter (24157): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter (24157): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter (24157): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:558:9)
E/flutter (24157): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
E/flutter (24157): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
E/flutter (24157): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
E/flutter (24157): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
E/flutter (24157): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
E/flutter (24157): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
E/flutter (24157): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
E/flutter (24157): #19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
E/flutter (24157): #20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter (24157): #21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter (24157): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter (24157): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter (24157): #24     _rootRunUnary (dart:async/zone.dart:1444:13)
E/flutter (24157): #25     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (24157): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (24157): #27     _invoke1 (dart:ui/hooks.dart:185:10)
E/flutter (24157): #28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
E/flutter (24157): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
```

**Comment by akbarraihanm** [comment]
how do you solve this?
