### ISSUE TITLE
Unhandled Exception: Bad state: No element

### ISSUE THREAD

**Issue by tmxdyf** [Milad-Akarie/auto_route_library#826]
log
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element
E/flutter (15915): #0      List.last (dart:core-patch/array.dart:310)
E/flutter (15915): #1      UrlState.flatten (package:auto_route/src/router/parser/route_information_parser.dart:69)
E/flutter (15915): #2      AutoRouterDelegate._onNewUrlState (package:auto_route/src/router/controller/auto_router_delegate.dart:103)
E/flutter (15915): #3      AutoRouterDelegate.setInitialRoutePath (package:auto_route/src/router/controller/auto_router_delegate.dart:72)
E/flutter (15915): #4      _rootRunUnary (dart:async/zone.dart:1436)
E/flutter (15915): <asynchronous suspension>
```
code

```dart
List<PageRouteInfo> initialRoutes;
    switch (uri.path) {
      case "/dictionary":
        initialRoutes = [
          HomeRoute(shouldShowUserGuide: false, children: [DictionaryRoute()])
        ];
        break;
      case "/overlay_window":
        initialRoutes = [OverlayWindowTranslateRoute()];// Executing this route causes this exception
        break;
      default:
        initialRoutes = [HomeRoute(shouldShowUserGuide: false)];
        break;
    }

    return MaterialApp.router(
      theme: lightTheme,
      darkTheme: lightTheme,
      // color: Colors.transparent,
      routeInformationParser: appRouter.defaultRouteParser(),
      routerDelegate: appRouter.delegate(
        navigatorObservers: () => [
          FirebaseAnalyticsObserver(analytics: analytics),
        ],
        initialRoutes: initialRoutes,
      ),
      supportedLocales: S.delegate.supportedLocales,
      localizationsDelegates: [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
        // LocaleNamesLocalizationsDelegate()
      ],
    );
```

**Comment by BenevidesLecontes** [comment]
I'm having this issue as well

**Comment by Milad-Akarie** [comment]
@tmxdyf no Idea why this happened but I added a check that should prevent the error anyways.
btw is there a reason why you're doing the matching your self? in most cases it's enough to just pass the deepLink/path to the route delegate?

**Comment by BenevidesLecontes** [comment]
In my case i'm just doing this
```
PageRouteInfo get _initialRoute {
    if (!isWhiteLabel || isWhiteLabelApp) {
      return LandPage();
    }
    return SplashScreenWhiteLabel();
  }
```

**Comment by Milad-Akarie** [comment]
@BenevidesLecontes is this still an issue in the latest build?

**Comment by BenevidesLecontes** [comment]
@Milad-Akarie i tried today, it's fine now.

**Comment by tmxdyf** [comment]
Thank you very much for your reply, it has been solved now, it is not the problem of autoRoute, it is caused by my incorrect use. Thank you.
@Milad-Akarie
