### ISSUE TITLE
Expected [HealthItemDetailArgs],  found [HealthItemDetailArgs]

### ISSUE THREAD

**Issue by CRDEV00** [Milad-Akarie/auto_route_library#989]
### I'm facing this instance problem while doing unit testing.

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Expected [HealthItemDetailArgs],  found [HealthItemDetailArgs]

When the exception was thrown, this was the stack:
#0      RouteData.argsAs (package:auto_route[/src/route/route_data.dart:46:7]())
#1      new MockAppRouter.<anonymous closure> ([src/test/mock_router.gr.dart:60:30]())
#2      RootStackRouter._pageBuilder (package:auto_route[/src/router/controller/root_stack_router.dart:97:20]())
#3      StackRouter._addEntry (package:auto_route[/src/router/controller/routing_controller.dart:1047:29]())
#4      StackRouter._push (package:auto_route[/src/router/controller/routing_controller.dart:870:14]())
<asynchronous suspension>

The test description was:
  Given a [loaded] state with data and TAPPING on an item should navigate to detail

This a testing issue, because it runs well in practice.

``` dart
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';

class HealthItemDetail extends StatelessWidget {
  final int id;
  final int type;

  const HealthItemDetail({
    @PathParam('id') required this.id,
    @PathParam('type') required this.type,
    Key? key,
  }) : super(key: key);


  @override
  Widget build(BuildContext context) {
    return const Center(key: Key('health-item-detail'), child: Text('DETAIL'));
  }
}
```

``` dart
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:widgets/health_items_detail.dart';

@MaterialAutoRouter(replaceInRouteName: 'Page,Route', routes: <AutoRoute>[
  AutoRoute(
      name: 'MockNestedRoute',
      page: MockNestedRouteWrapper,
      path: 'mockNestedRouteWrapper',
      children: [
        MaterialRoute(path: 'home', name: 'Home', page: MockDashboardPageWrapper, children: [
          MaterialRoute(
            path: '',
            page: InitialRoutePage,
            initial: true,
          ),
          CustomRoute(
              path: 'healthItemDetail/:id/:type',
              page: HealthItemDetail,
              transitionsBuilder: TransitionsBuilders.fadeIn,
              durationInMilliseconds: 400),
          RedirectRoute(path: '*', redirectTo: ''),
        ])
      ])
])
class $MockAppRouter {}

class MockNestedRouteWrapper extends StatelessWidget {
  const MockNestedRouteWrapper({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const AutoRouter();
  }
}

class InitialRoutePage extends StatelessWidget {
  const InitialRoutePage({Key? key, required this.child}) : super(key: key);

  final Widget child;

  @override
  Widget build(BuildContext context) {
    return child;
  }
}

class MockDashboardPageWrapper extends StatelessWidget {
  const MockDashboardPageWrapper({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const AutoRouter();
  }
}
```
``` dart
class ClaimTabletList extends StatelessWidget {
  const ClaimTabletList({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<HealthDataCubit, HealthDataState>(
      buildWhen: (HealthDataState previous, HealthDataState current) {
        return current.status == PageStateStatus.loaded ||
            current.status == PageStateStatus.updated;
      },
      builder: (context, state) {
        return ListView.builder(
          itemCount: state.data!.claims.length,
          itemBuilder: (context, index) {
            return GestureDetector(
              onTap: () {
                AutoRouter.of(context).push(
                  HealthItemDetail(
                    id: state.data!.claims[index].id,
                    type: FeatureModuleConfigType.Claims.index,
                  ),
                );
              },
              child: Container(
                margin: const EdgeInsets.only(left: 15, bottom: 10, top: 10),
                child: ClaimLisItem(
                  claims: state.data!.claims,
                  index: index,
                ),
              ),
            );
          },
        );
      },
    );
  }
}

```

``` dart
testWidgets('Given a [loaded] state with data and TAPPING on an item should navigate to detail',
      (tester) async {
    final testableWidget = testableWrapper(
        child: const ClaimTabletList(),
        blocProviders: [BlocProvider<HealthDataCubit>(create: ((context) => mockHealthDataCubit))]);
    final data = generateHealthDataState(
        status: PageStateStatus.loaded,
        data: generateHealthData(claims: [
          generateClaim(
            id: 1,
            remainingMemberResponsibilityAmount: 120,
            transactionsSum: 100,
          ),
          generateClaim(
            id: 2,
            remainingMemberResponsibilityAmount: 120,
            transactionsSum: 100,
          )
        ]));
    when(() => mockHealthDataCubit.state).thenReturn(data);
    await tester.pumpWidget(testableWidget);
    await tester.pumpAndSettle();
    expect(find.byType(ListView), findsOneWidget);
    expect(find.byType(ClaimLisItem), findsNWidgets(data.data!.claims.length));
    await tester.tap(find.byType(GestureDetector).first);
    await tester.pumpAndSettle();
    expect(find.byType(HealthItemDetail), findsOneWidget);
  });
```

**Comment by dius00** [comment]
@CRDEV00 I just found myself having to deal with this issue as well earlier today, and wanted to share info about what might be the cause of it and shed some clarity.

When your `AutoRouter.of(context).push(HealthItemDetail(...))` is called, in the file generated by `$MockAppRouter` the following will be executed.
```dart
HealthItemDetailRoute.name: (routeData) {
      final args = routeData.argsAs<HealthItemDetailRouteArgs>(); // This is what throws specifically.
      return _iX.CustomPage<dynamic>(
          ...)
    },
 ```
Your `.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.4/lib/src/route/route_data.dart` will contain the `argsAs` method. If you modify it to add a print statement you will have the following.

```dart
  T argsAs<T>({T Function()? orElse}) {
    final args = _match.args;
    if (args == null) {
      if (orElse == null) {
        throw FlutterError(
            '${T.toString()} can not be null because it has a required parameter');
      } else {
        return orElse();
      }
    } else if (args is! T) {
      print(T);                 //HealthItemDetailRoute
      print(args.runtimeType);  //HealthItemDetailRoute
      print(T.hashCode);        // X
      print(args.hashCode);     // Y 
      print(args is T);         // false
      throw FlutterError(
          'Expected [${T.toString()}],  found [${args.runtimeType}]');
    } else {
      return args;
    }
  }
  ```

The reason for the different `hashcode` for what apparently seems the same `Type` is due to the imports.

While you are using `MockAppRouter` in the test, that is likely not your router in the file where your `ClaimTabletList` is declared. This causes it to use the `HealthItemDetailRoute` of the original `nonMockRouter.gr.dart` and try to compare it with the `HealthItemDetailRoute` of your `mockRouter.gr.dart` causing the `hashCode` mismatch. 

While I was able to fix the issue on my side with conditional import since my routing issue was caused by slightly different routers on `web` vs `other` I don't think the same solution could be applied here.

In your situation, I am not sure how to fix the issue on your side, given that conditional imports might not be an option. I believe you could refactor the test to check that the `AutoRouter.of(context).push` has been called, and the arguments it was called with, followed by a test that when `HealthItemDetailRoute` is called with `X` arguments the widget is built properly.

**Comment by CRDEV00** [comment]
HI @dius00  ! thanks for letting me know this. It helped me to fixed my issue.  What I did was passing the route as parameter to the widgets I was testing, this way in testing the routing is coming from the same auto generated file.
